/**
 * IPC Types Index
 * Unified export of all IPC-related type definitions
 *
 * This file aggregates and re-exports all types from the modular structure,
 * maintaining backward compatibility with existing imports from '../shared/ipc.js'
 */

// IPC Channel Constants
export { IPC_CHANNELS } from "./channels.js";

export {
	DEFAULT_AGENT_ID,
	agentIdentity,
	isColleague,
	isActiveAgent,
} from "./agents.js";
export type {
	CollabAgentActivityGetRequest,
	CollabAgentActivityGetResponse,
	CollabAgentActivitySnapshot,
	CollabAgentHeldLease,
	CollabAgentMind,
	CollabAgentWorkerCard,
	CollabBoard,
	CollabBoardAction,
	CollabBoardActRequest,
	CollabBoardActResponse,
	CollabBoardGetRequest,
	CollabBoardGetResponse,
	CollabDmRoomEnsureRequest,
	CollabDmRoomEnsureResponse,
	CollabMessageReactRequest,
	CollabMessageReactResponse,
	CollabRoomBudgetsPatch,
	CollabRoomBudgetsRequest,
	CollabRoomBudgetsResponse,
	CollabRoomFolderEntry,
	CollabRoomFolderListRequest,
	CollabRoomFolderListResponse,
	CollabRoomFrozenRequest,
	CollabRoomFrozenResponse,
	CollabCoordinatorBlockedBy,
	CollabCoordinatorGate,
	CollabCoordinatorGetRequest,
	CollabCoordinatorGetResponse,
	CollabCoordinatorJudgment,
	CollabCoordinatorLogEntry,
	CollabCoordinatorPhase,
	CollabCoordinatorQueued,
	CollabCoordinatorState,
	CollabCoordinatorTurn,
	CollabRoomClearHistoryRequest,
	CollabRoomClearHistoryResponse,
	CollabRoomRevokeLeaseFailure,
	CollabRoomRevokeLeaseRequest,
	CollabRoomRevokeLeaseResponse,
	CollabRoomRevokeLeaseResult,
	CollabRoomSpendRequest,
	CollabRoomSpendResponse,
	CollabRoomUpdatePatch,
	CollabRoomUpdateRequest,
	CollabRoomUpdateResponse,
	CollabSchedulerLogEntry,
	CollabSchedulerLogTailRequest,
	CollabSchedulerLogTailResponse,
	CollabTask,
	CollabTaskEvidence,
	CollabTaskStatus,
	CollabTaskStopRequest,
	CollabTaskStopResponse,
} from "./collab.js";
export type {
	OriginTransport,
	ConversationType,
	ResolvedIdentityKind,
	ChannelActor,
	ChannelConversation,
	ReplyTarget,
	ResolvedIdentity,
	MessageOrigin,
	PluginMessageOriginStamp,
	IMConnectorIncomingMessage,
	IMConnectorReplyPayload,
	IMConnector,
	ChannelUserLink,
	ChannelUserProfile,
	ChannelIdentityListProfilesResponse,
	ChannelIdentityCreateProfileRequest,
	ChannelIdentityCreateProfileResponse,
	ChannelIdentityUpdateProfileRequest,
	ChannelIdentityUpdateProfileResponse,
	ChannelIdentityListLinksRequest,
	ChannelIdentityListLinksResponse,
	ChannelIdentityCreateLinkRequest,
	ChannelIdentityCreateLinkResponse,
	ChannelIdentityDeleteLinkRequest,
	ChannelIdentityDeleteLinkResponse,
	ChannelIdentityResolveRequest,
	ChannelIdentityResolveResponse,
	ChannelReplyDeliveryRecord,
	ChannelDeliveryListResponse,
	ChannelIdentityRoutes,
} from "./channel-identity.js";
export { channelIdentityRouter } from "./channel-identity.js";
export type {
	AgentDefinition,
	AgentIdentity,
	AgentKind,
	AgentStatus,
	AgentExecutor,
	AgentModelBinding,
	AgentsListResponse,
	AgentCreateRequest,
	AgentCreateResponse,
	AgentUpdateRequest,
	AgentUpdateResponse,
	AgentDeleteRequest,
	AgentDeleteResponse,
	AgentRemovalOutcome,
	AgentRestoreRequest,
	AgentRestoreResponse,
	AgentsRoutes,
} from "./agents.js";
export { agentsRouter } from "./agents.js";

// IPC Router infrastructure
export { defineRouter, getChannelName } from "./router.js";
export type {
	RouteConfig,
	DomainRoutes,
	Router,
	RouteHandlers,
	RouteAPI,
} from "./router.js";

// Tool types
export type {
	GetToolsResponse,
	ExecuteToolRequest,
	ExecuteToolResponse,
	ToolParameter,
	ToolDefinition,
	ToolCall,
	DiffHunk,
	DiffHunkLine,
	ToolResultContentPart,
	ToolResult,
	ToolPartialResult,
	ToolExecutionMode,
	ToolRenderShell,
	ToolRenderKind,
	PermissionMode,
	BashToolSettings,
	ToolCallModelSettings,
	ToolSettings,
	StreamMessageChunk,
	SendMessageStreamResponse,
} from "./tools.js";

// Chat types
export type {
	VoiceASRProvider,
	VoiceTTSProvider,
	VoiceEndpointingMode,
	VoiceWakeSensitivity,
	VoiceDoubaoSettings,
	VoiceAudioChunkPayload,
	VoiceRuntimeStatus,
	VoiceWakeSettings,
	VoiceVADSettings,
	VoiceASRSettings,
	VoiceTTSSettings,
	VoiceConversationSettings,
	VoiceSettings,
	VoiceTranscriptMetadata,
	VoiceLatencyMilestone,
	VoiceLatencyMilestoneName,
	VoiceRuntimeState,
	VoiceEvent,
	VoiceRuntimeEvent,
	VoiceRuntimeCommand,
	VoiceStartRequest,
	VoiceStopRequest,
	VoiceSubmitUtteranceRequest,
	VoiceSubmitTranscriptRequest,
	VoiceSynthesizeRequest,
	VoiceTestASRRequest,
	VoiceTestTTSRequest,
	VoiceTTSModel,
	VoiceBaseResponse,
	VoiceGetStateResponse,
	VoiceSubmitUtteranceResponse,
	VoiceSynthesizeResponse,
	VoiceTTSModelsResponse,
} from "./voice.js";

export type {
	MusicPlayerBackend,
	MusicRadioSource,
	MusicSetupStage,
	MusicToolStatus,
	MusicEnvStatus,
	MusicRuntimeState,
	MusicBaseResponse,
	MusicListProvidersResponse,
	MusicGetProgrammeResponse,
	MusicOpenRadioRequest,
	MusicSearchRequest,
	MusicSearchResponse,
	MusicSearchRecordDTO,
	MusicRequestSongRequest,
	MusicRequestSongResponse,
	MusicProgrammeActionRequest,
	MusicProgrammeEntryDTO,
	MusicProgrammeAction,
	MusicProviderDescriptorDTO,
	MusicSetProviderRequest,
	MusicGetStateResponse,
	MusicSetupRequest,
	MusicSetupResponse,
	MusicEvent,
	MusicSettings,
	MusicNowPlaying,
	MusicCommand,
	MusicCommandRequest,
	MusicCommandResponse,
	MusicRadioState,
	MusicLyricLine,
	MusicLyrics,
	MusicDjSpeak,
} from "./music.js";

export type {
	ContextVariable,
	VariableLevel,
	ContentPart,
	StepType,
	Step,
	AttachmentMediaType,
	MessageAttachment,
	ChatMessage,
	ChatMessageMention,
	ChatMessageReaction,
	ChatMessageReactionActor,
	ChatMessageReplyTo,
	PromptContextRole,
	BaseInstructions,
	PromptContextMarker,
	PromptContextFragment,
	TurnContextSnapshot,
	PromptContextState,
	// Session-level optimization (Phase 4: Metadata Separation)
	SessionMeta,
	SessionDetails,
	ChatSession,
	SendMessageRequest,
	SendMessageResponse,
	EditAndResendRequest,
	EditAndResendResponse,
	GetChatHistoryRequest,
	GetChatHistoryResponse,
	GetSessionsResponse,
	CreateSessionRequest,
	CreateSessionOptions,
	CreateSessionResponse,
	SwitchSessionRequest,
	SwitchSessionResponse,
	DeleteSessionRequest,
	DeleteSessionResponse,
	RenameSessionRequest,
	RenameSessionResponse,
	CreateBranchRequest,
	CreateBranchResponse,
	UpdateSessionPinRequest,
	UpdateSessionPinResponse,
	GenerateTitleRequest,
	GenerateTitleResponse,
	SystemPromptToolSnapshot,
	SystemPromptSkillSnapshot,
	SystemPromptSnapshot,
	GetSystemPromptSnapshotRequest,
	GetSystemPromptSnapshotResponse,
	// Optimized session loading (Phase 4)
	GetSessionsListResponse,
	ActivateSessionResponse,
	GetSessionMessagesResponse,
	SessionMessagesPageDirection,
	SessionMessagesPageAnchor,
	GetSessionMessagesPageRequest,
	SessionMessagePageCursor,
	GetSessionMessagesPageResponse,
	UserMessageMarker,
	GetSessionUserMarkersResponse,
} from "./chat.js";

// Media types
export type {
	MediaKind,
	MediaSource,
	MediaUsageTag,
	MediaAssetLink,
	MediaAssetMetadata,
	MediaAsset,
	MediaQuery,
	MediaIngestFileInput,
	MediaIngestFilesRequest,
	MediaIngestFilesResponse,
	MediaSaveAsRequest,
	MediaSaveAsResponse,
	MediaGalleryResponse,
	MediaRebuildResponse,
	MediaLegacyItem,
	MediaSaveImageRequest,
	MediaPreviewLookupResponse,
	MediaRoutes,
} from "./media.js";
export { mediaRouter } from "./media.js";

// 会话命令总线的入口(结构债 P4c 第四批)。命令的**词汇表与载荷**仍在
// `@shared/events/session-commands.ts`,这里只有「怎么过线」那一半。
export type {
	SessionCommandEmitRequest,
	SessionCommandEmitResult,
	SessionCommandRoutes,
} from "./session-command.js";
export { sessionCommandRouter } from "./session-command.js";

// Markdown asset / attachment types
export type {
	MarkdownAssetKind,
	MarkdownAssetResolution,
	MarkdownResolveAssetRequest,
	MarkdownResolveAssetResponse,
	MarkdownAttachmentInput,
	SavedMarkdownAttachment,
	MarkdownSaveAttachmentsRequest,
	MarkdownSaveAttachmentsResponse,
} from "./markdown.js";

// Provider types
export type {
	AIProviderId,
	ThinkingEffort,
	OAuthFlowType,
	OAuthToken,
	OpenRouterModel,
	ProviderInfo,
	ProviderConfig,
	ModelCapabilityOverride,
	CustomProviderConfig,
	AISettings,
	EffectiveAISettings,
	SpaceProviderSettings,
	ProviderModelCatalog,
	ModelCapabilityEntry,
	ModelType,
	ModelInfo,
	GetProvidersResponse,
	CodexUsageWindow,
	CodexUsageCredits,
	CodexUsageLimit,
	CodexProviderUsage,
	ProviderUsageRequest,
	ProviderUsageResponse,
	ProviderEnvVarCandidate,
	ProviderEnvStatus,
	GetProviderEnvStatusRequest,
	GetProviderEnvStatusResponse,
	ModelsListResponse,
	ModelsWithCapabilitiesRequest,
	ModelsSearchRequest,
	ModelRefreshRegistryResponse,
	ModelNameAliasesResponse,
	ModelDisplayNameRequest,
	ModelDisplayNameResponse,
	ProvidersRoutes,
	ModelsRoutes,
} from "./providers.js";

export { AIProvider, modelsRouter, providersRouter } from "./providers.js";

// MCP types
export type {
	MCPTransportType,
	MCPServerConfig,
	MCPConnectionStatus,
	MCPToolInfo,
	MCPResourceInfo,
	MCPPromptInfo,
	MCPServerState,
	MCPSettings,
	MCPGetServersResponse,
	MCPAddServerRequest,
	MCPAddServerResponse,
	MCPUpdateServerRequest,
	MCPUpdateServerResponse,
	MCPRemoveServerRequest,
	MCPRemoveServerResponse,
	MCPConnectServerRequest,
	MCPConnectServerResponse,
	MCPDisconnectServerRequest,
	MCPDisconnectServerResponse,
	MCPLogoutServerRequest,
	MCPLogoutServerResponse,
	MCPProbeServerRequest,
	MCPProbeServerResponse,
	MCPRefreshServerRequest,
	MCPRefreshServerResponse,
	MCPGetToolsResponse,
	MCPCallToolRequest,
	MCPCallToolResponse,
	MCPGetResourcesResponse,
	MCPReadResourceRequest,
	MCPReadResourceResponse,
	MCPGetPromptsResponse,
	MCPGetPromptRequest,
	MCPGetPromptResponse,
	MCPReadConfigFileRequest,
	MCPReadConfigFileResponse,
} from "./mcp.js";

// ACP types
export type {
	ACPConnectionStatus,
	ACPPermissionMode,
	ACPAgentConfig,
	ACPAgentState,
	ACPSettings,
	ACPGetAgentsResponse,
	ACPAddAgentRequest,
	ACPAddAgentResponse,
	ACPUpdateAgentRequest,
	ACPUpdateAgentResponse,
	ACPRemoveAgentRequest,
	ACPRemoveAgentResponse,
	ACPConnectAgentRequest,
	ACPConnectAgentResponse,
	ACPDisconnectAgentRequest,
	ACPDisconnectAgentResponse,
	ACPRefreshAgentRequest,
	ACPRefreshAgentResponse,
	ACPCancelSessionRequest,
	ACPCancelSessionResponse,
} from "./acp.js";

// OAuth types
export type {
	OAuthCredentialTargetRequest,
	OAuthStartRequest,
	OAuthStartResponse,
	OAuthCallbackRequest,
	OAuthCallbackResponse,
	OAuthStatusRequest,
	OAuthStatusResponse,
	OAuthLogoutRequest,
	OAuthLogoutResponse,
	OAuthDevicePollRequest,
	OAuthDevicePollResponse,
} from "./oauth.js";

// Skills types
export type {
	SkillSource,
	SkillDefinition,
	SkillConditions,
	SkillReferenceSnapshot,
	SkillFile,
	SkillSettings,
	GetSkillsRequest,
	GetSkillsResponse,
	RefreshSkillsResponse,
	ReadSkillFileRequest,
	ReadSkillFileResponse,
	OpenSkillDirectoryRequest,
	OpenSkillDirectoryResponse,
	CreateSkillRequest,
	CreateSkillResponse,
	DeleteSkillRequest,
	DeleteSkillResponse,
	ToggleSkillEnabledRequest,
	ToggleSkillEnabledResponse,
	SkillDirectoryConfig,
	ListSkillDirectoriesResponse,
	AddSkillDirectoryRequest,
	AddSkillDirectoryResponse,
	UpdateSkillDirectoryRequest,
	UpdateSkillDirectoryResponse,
	RemoveSkillDirectoryRequest,
	RemoveSkillDirectoryResponse,
	SetSkillAgentRequest,
	SetSkillAgentResponse,
	SkillsRoutes,
} from "./skills.js";
export { skillsRouter } from "./skills.js";

// Plugin types
export type {
	PluginCommandInfo,
	GetPluginCommandsResponse,
	ExecutePluginCommandRequest,
	ExecutePluginCommandResponse,
	PluginRequestPayload,
	PluginRequestResult,
	PluginRequestProgressPayload,
	AbortPluginRequestResult,
	PluginNotificationPayload,
	PluginConfigFieldDescriptor,
	PluginConfigErrorDetail,
	PluginConfigRequest,
	PluginConfigResponse,
	SetPluginConfigRequest,
	SetPluginConfigResponse,
	UninstallPluginRequest,
	UninstallPluginResponse,
	InstallPluginRequest,
	InstallPluginResponse,
	UpdatePluginRequest,
	UpdatePluginResponse,
	PluginUpdateOffer,
	CheckPluginUpdatesResponse,
	PluginLifecycleInfoResponse,
	ReadPluginTarballRequest,
	ReadPluginTarballErrorCode,
	PluginTarballSummary,
	ReadPluginTarballResponse,
	PluginDataFootprint,
	PluginFootprintResponse,
	PluginMarketEntryView,
	GetPluginMarketRequest,
	GetPluginMarketResponse,
	PickPluginFileRequest,
	PickPluginFileResponse,
} from "./plugins.js";

// Plugin market index URL(P3 裁决:纯硬编码;唯一事实源)
export { PLUGIN_MARKET_INDEX_URL } from "./plugins.js";

// Scheduler types
export type {
	SchedulerRunReason,
	SchedulerTaskKind,
	SchedulerTaskSource,
	SchedulerRunStatus,
	SchedulerSchedule,
	SchedulerRunRecordDTO,
	SchedulerRunTimelineEntryDTO,
	SchedulerRunToolCallDTO,
	SchedulerRunStepDTO,
	SchedulerRunDetailDTO,
	SchedulerTaskSnapshotDTO,
	SchedulerUserTaskDTO,
	SchedulerListResponse,
	SchedulerGetRequest,
	SchedulerGetResponse,
	SchedulerRunNowRequest,
	SchedulerRunNowResponse,
	SchedulerSetEnabledRequest,
	SchedulerSetEnabledResponse,
	SchedulerCreateTaskRequest,
	SchedulerUpdateTaskRequest,
	SchedulerDeleteTaskRequest,
	SchedulerWriteTaskResponse,
	SchedulerDeleteTaskResponse,
	SchedulerListRunsRequest,
	SchedulerListRunsResponse,
	SchedulerGetRunRequest,
	SchedulerGetRunResponse,
} from "./scheduler.js";

// Settings types
export type {
	ColorTheme,
	MessageListDensity,
	TypographyDensity,
	BaseTheme,
	KeyboardShortcut,
	ShortcutSettings,
	EditorSettings,
	GeneralSettings,
	ChatSettings,
	NetworkSettings,
	ProxySettings,
	WechatChannelSettings,
	ChannelSettings,
	EvalsSettings,
	AppSettings,
	PersistedAppSettings,
	GetSettingsResponse,
	SaveSettingsRequest,
	SaveSettingsResponse,
	TestProxyRequest,
	TestProxyResponse,
} from "./settings.js";

export type {
	GatewayChannelId,
	GatewayWechatLoginStatus,
	GatewayWechatStatus,
	GatewayWechatAccountStatus,
	GatewayStatus,
	GatewayGetStatusResponse,
	GatewayStartRequest,
	GatewayStartResponse,
	GatewayStopResponse,
	GatewayWechatAddAccountRequest,
	GatewayWechatAddAccountResponse,
	GatewayWechatStopAccountRequest,
	GatewayWechatStopAccountResponse,
	GatewayWechatRemoveAccountRequest,
	GatewayWechatRemoveAccountResponse,
	GatewayWechatRenameAccountRequest,
	GatewayWechatRenameAccountResponse,
	GatewayWechatLogoutRequest,
	GatewayWechatLogoutResponse,
} from "./gateway.js";

// Theme types
export type {
	ColorValue,
	ThemeDefs,
	ThemeBgColors,
	ThemeTextColors,
	ThemeBorderColors,
	ThemeShadows,
	ThemeEffects,
	ThemeNeutralColors,
	SemanticHighlightToken,
	HighlightFontStyle,
	HighlightStyle,
	HighlightLink,
	ThemeHighlightGroup,
	ThemeHighlights,
	SemanticUIToken,
	UIStyle,
	UILink,
	ThemeUIGroup,
	ThemeUITokens,
	ThemeColors,
	Theme,
	ThemeMeta,
	Base46Base30,
	Base46Base16,
	Base46Theme,
	GetThemesResponse,
	GetThemeResponse,
	ApplyThemeResponse,
	RefreshThemesResponse,
} from "./themes.js";

// Permission types
export type {
	PermissionInfo,
	PermissionResponse,
	PermissionRespondRequest,
} from "./permissions.js";

// Interaction types (agent 提问 → 用户应答;与 Permission 并列的一等概念)
export type {
	InteractionAnswer,
	InteractionGetPendingRequest,
	InteractionGetPendingResponse,
	InteractionOption,
	InteractionOrigin,
	InteractionOutcome,
	InteractionQuestion,
	InteractionQuestionAnswer,
	InteractionRequest,
	InteractionRespondRequest,
	InteractionRespondResponse,
} from "./interaction.js";

// Variable types
export type {
	VariablesListRequest,
	VariablesListResponse,
	VariablesSetRequest,
	VariablesSetResponse,
	VariablesDeleteRequest,
	VariablesDeleteResponse,
} from "./variables.js";

// Session goal types
export type {
	SessionGoal,
	SessionGoalStatus,
	GoalGetRequest,
	GoalGetResponse,
	GoalSetAction,
	GoalSetRequest,
	GoalSetResponse,
	GoalFileDiff,
	GoalDiffsRequest,
	GoalDiffsResponse,
	GoalRoutes,
} from "./goal.js";
export { goalRouter } from "./goal.js";

// Session TOC (table of contents) types
export type {
	SessionSegment,
	SessionSegmentFile,
	SessionSegmentKind,
	SessionSegmentOrigin,
	SessionSegmentOutcome,
	GetSessionSegmentsResponse,
} from "./toc.js";

// Project directories types
export type {
	ProjectDirSummary,
	ProjectDirRecord,
	ProjectDirsWorkspaceScoped,
	ProjectDirsListRequest,
	ProjectDirsListResponse,
	ProjectDirsGetRequest,
	ProjectDirsGetResponse,
	ProjectDirsAddRequest,
	ProjectDirsAddResponse,
	ProjectDirsUpdateRequest,
	ProjectDirsUpdateResponse,
	ProjectDirsRemoveRequest,
	ProjectDirsRemoveResponse,
} from "./project-dirs.js";

// Space (workspace) types
export type {
	SpaceRecord,
	SpacesListResponse,
	SpacesCreateRequest,
	SpacesCreateResponse,
	SpacesUpdateRequest,
	SpacesUpdateResponse,
	SpacesRemoveRequest,
	SpacesRemoveResponse,
	SpaceOverlayPayload,
	SpacesChangedEvent,
	SpacesGetOverlayRequest,
	SpacesGetOverlayResponse,
	SpacesSetOverlayRequest,
	SpacesSetOverlayResponse,
	SpacesGetProviderSettingsRequest,
	SpacesGetProviderSettingsResponse,
	SpacesSetProviderSettingsRequest,
	SpacesSetProviderSettingsResponse,
	SpaceCredentialEntrySummary,
	SpaceCredentialStrategySummary,
	SpaceProviderCredentialSummary,
	SpaceCredentialsSummary,
	SpaceCredentialImportSkip,
	SpacesGetCredentialsRequest,
	SpacesGetCredentialsResponse,
	SpacesSetCredentialRequest,
	SpacesSetCredentialResponse,
	SpacesSetCredentialPoolRequest,
	SpacesSetCredentialPoolResponse,
	SpacesClearCredentialRequest,
	SpacesClearCredentialResponse,
	SpacesImportCredentialsRequest,
	SpacesImportCredentialsResponse,
} from "./spaces.js";

// UIMessage types
export type {
	ToolUIState,
	TextUIPart,
	ReasoningUIPart,
	FileUIPart,
	ToolUIPart,
	StepStartUIPart,
	StepsDataUIPart,
	ErrorDataUIPart,
	UIMessagePart,
	StepUIPart,
	ErrorUIPart,
	MessageMetadata,
	UIMessage,
	UIMessageChunk,
	UIMessagePartChunk,
	TokenUsage,
	SessionTokenUsage,
	UIMessageFinishChunk,
	UIMessageStreamData,
} from "./ui-message.js";

export {
	isTextUIPart,
	isReasoningUIPart,
	isToolUIPart,
	isFileUIPart,
	isStepUIPart,
	isErrorUIPart,
	getToolName,
} from "./ui-message.js";

// Search types
export {
	SEARCH_CATEGORIES,
	isSearchCategory,
} from "./search.js";

export type {
	SearchCategory,
	SearchRequest,
	SearchResult,
	SearchResponse,
	SearchWindowGuideState,
	SearchWindowSplitIntent,
	SearchWindowIntent,
	SearchWindowOpenOptions,
	SearchWindowShownPayload,
	SearchWindowAnchor,
} from "./search.js";

// User prompt snippet types
export type {
	UserPrompt,
	PromptReferenceSnapshot,
	PromptListResponse,
	PromptGetRequest,
	PromptGetResponse,
	PromptCreateRequest,
	PromptCreateResponse,
	PromptUpdateRequest,
	PromptUpdateResponse,
	PromptDeleteRequest,
	PromptDeleteResponse,
	PromptsRoutes,
} from "./prompts.js";
export { promptsRouter } from "./prompts.js";

// Todo / plan panel types
export type {
	TodoPlanScope,
	TodoPlanActivationMode,
	TodoPlanAutonomyMode,
	TodoPlanWindowActionRequest,
	TodoPlanWindowDragPhase,
	TodoPlanWindowDragRequest,
	TodoPlanDocument,
	TodoPlanContext,
	TodoPlanSnapshot,
	TodoPlanSettings,
	TodoPlanGetRequest,
	TodoPlanGetResponse,
	TodoPlanCreateRequest,
	TodoPlanCreateResponse,
	TodoPlanUpdateRequest,
	TodoPlanUpdateResponse,
	TodoPlanRenameRequest,
	TodoPlanRenameResponse,
	TodoPlanDeleteRequest,
	TodoPlanDeleteResponse,
	TodoPlanChangedPayload,
	TodoPlanRevealDirectoryResponse,
	TodoPlanRoutes,
} from "./todo-plan.js";
export { todoPlanRouter } from "./todo-plan.js";

// Scratchpad types
export type {
	ScratchpadDocument,
	ScratchpadGetRequest,
	ScratchpadGetResponse,
	ScratchpadUpdateRequest,
	ScratchpadUpdateResponse,
	ScratchpadDeleteRequest,
	ScratchpadDeleteResponse,
	ScratchpadAdoptRequest,
	ScratchpadAdoptResponse,
	ScratchpadChangedPayload,
} from "./scratchpad.js";

// Evals types
export type {
	EvalsRecordDownvoteRequest,
	EvalsRecordDownvoteResponse,
	TurnEvalRecord,
	EvalsListRecordsRequest,
	EvalsListRecordsResponse,
	TurnEvalRecordView,
	EvalsListFixturesResponse,
	EvalFixtureMeta,
	EvalsReadFixtureRequest,
	EvalsReadFixtureResponse,
	EvalsListResultsResponse,
	EvalRunResultEntry,
	EvalsListCasesResponse,
	EvalCaseMeta,
	EvalsGetCaseRequest,
	EvalsGetCaseResponse,
	EvalsRunStartRequest,
	EvalsRunStartResponse,
	EvalsRunCancelResponse,
	EvalsRunProgressEvent,
	EvalsPromoteFixtureRequest,
	EvalsPromoteFixtureResponse,
	EvalsRetireCaseRequest,
	EvalsRetireCaseResponse,
	EvalsGenerateTriageRequest,
	EvalsGenerateTriageResponse,
	EvalsReadRunDetailRequest,
	EvalsReadRunDetailResponse,
	EvalRunCaseAttempt,
	EvalRunCaseDetail,
	EvalRunDetail,
	EvalsReadSnapshotRequest,
	EvalsReadSnapshotResponse,
	PromptSnapshotView,
	ContextSnapshotMessage,
	EvalsIncidentMetaDTO,
	EvalsIncidentListResponse,
	EvalsIncidentGetRequest,
	EvalsIncidentGetResponse,
	EvalsIncidentRunSummary,
	EvalsIncidentUpdateRequest,
	EvalsIncidentUpdateResponse,
	EvalsIncidentReadFileRequest,
	EvalsIncidentReadFileResponse,
	EvalsReplayStartRequest,
	EvalsReplayStartResponse,
	EvalsReplayProgressEvent,
	EvalsIncidentAnalyzeRequest,
	EvalsIncidentAnalyzeResponse,
	EvalsIncidentPromoteRequest,
	EvalsIncidentPromoteResponse,
	EvalsDiagnoseStartRequest,
	EvalsDiagnoseStartResponse,
	EvalsDiagnoseProgressEvent,
	EvalsRoundListRequest,
	EvalsRoundView,
	EvalsRoundListResponse,
	EvalsRoundReplayRequest,
	EvalsRoundReplayResponse,
} from "./evals.js";

export type {
	GetSessionUsageRequest,
	GetSessionUsageResponse,
	GetUsageSummaryRequest,
	GetUsageSummaryResponse,
	OnethingUsageBreakdownEntry,
	OnethingUsageBucket,
	OnethingUsagePricingQuality,
	OnethingUsageProjectTotals,
	OnethingUsageSummaryGranularity,
	UsageRoutes,
} from "./usage.js";
export { usageRouter } from "./usage.js";

export type { RpcDispatchContext, RpcError, RpcErrorCode, RpcRequest, RpcResponse } from "./rpc.js";
export { DESKTOP_RPC_CONTEXT, RPC_ERROR_CODES } from "./rpc.js";

export type {
	PracticeConfig,
	PracticeConfigResponse,
	PracticeEventPayload,
	PracticeLedgerRecord,
	PracticeLogRequest,
	PracticeLogResponse,
	PracticePhaseEdge,
	PracticeRecentRequest,
	PracticeRecentResponse,
	PracticeSetConfigRequest,
	PracticeSnapshot,
	PracticeStartRequest,
	PracticeStateResponse,
	PracticeStopRequest,
	PracticeSummaryGranularity,
	PracticeSummaryRequest,
	PracticeSummaryResult,
} from "./practice.js";

export type {
	NotifyActivateEvent,
	NotifySimpleResponse,
	SetBadgeRequest,
	ShowNotificationRequest,
} from "./notify.js";

export type {
	TerminalAckPayload,
	TerminalAttachRequest,
	TerminalAttachResponse,
	TerminalCreateRequest,
	TerminalCreateResponse,
	TerminalDataEvent,
	TerminalExitEvent,
	TerminalInfo,
	TerminalKillRequest,
	TerminalListResponse,
	TerminalOutputChunk,
	TerminalResizeRequest,
	TerminalSimpleResponse,
	TerminalWriteRequest,
} from "./terminal.js";

export type {
	BrowserCreateTabRequest,
	BrowserCreateTabResponse,
	BrowserHydrateResponse,
	BrowserNavigateRequest,
	BrowserSetBoundsRequest,
	BrowserSetVisibleRequest,
	BrowserSimpleResponse,
	BrowserAddProfileRequest,
	BrowserPickResponse,
	BrowserProfile,
	BrowserProfileIdRequest,
	BrowserProfilesResponse,
	BrowserSearchEngine,
	BrowserSearchEngineId,
	BrowserSearchEngineResponse,
	BrowserSetSearchEngineRequest,
	BrowserTabIdRequest,
	BrowserTabInfo,
	BrowserTabsChangedEvent,
	BrowserViewBounds,
	PickedWebElement,
} from "./browser.js";

export {
	BROWSER_SEARCH_ENGINES,
	DEFAULT_BROWSER_SEARCH_ENGINE_ID,
	isBrowserSearchInput,
	resolveBrowserOmniboxInput,
	resolveBrowserSearchEngine,
} from "./browser.js";
