/**
 * Tools Module
 * Tool-related type definitions for IPC communication
 */

import type { ThinkingEffort } from './providers.js'
import type { JsonObject, JsonSchemaObject, JsonValue } from '../json.js'

// Tool related types
export interface GetToolsResponse {
  success: boolean
  tools?: ToolDefinition[]
  error?: string
}

export interface ExecuteToolRequest {
  toolId: string
  arguments: JsonObject
  messageId: string  // Associated message ID
  sessionId: string
  /** Optional stable invocation ID for subsequent targeted cancellation. */
  toolCallId?: string
}

export interface ExecuteToolResponse {
  success: boolean
  result?: JsonValue
  error?: string
}

export interface ToolParameter {
  name: string
  type: 'string' | 'number' | 'boolean' | 'object' | 'array'
  description: string
  required?: boolean
  enum?: string[]
  default?: JsonValue
}

export interface ToolDefinition {
  id: string
  name: string
  description: string
  parameters: ToolParameter[]
  /** Full JSON Schema for tool parameters. Preserves nested array/object shapes for model-facing schemas. */
  parameterSchema?: JsonSchemaObject
  // Permission settings
  enabled: boolean           // Whether this tool is enabled
  autoExecute: boolean       // Whether to auto-execute when called
  /**
   * @deprecated R4b —— 概念已退役。权限只认 `Intent.effects`(见
   * `packages/core/toolkit/effects.ts` 的策略表);这个字段活着只是因为契约与
   * 渲染层还在读它,它的值由 `app/toolkit/guard-projection.ts` 从 `spec.effects`
   * **派生**。没有任何工具作者再写它,也没有任何判定读它做决定。
   */
  permissionGuard?: 'safe' | 'sandboxed' | 'internal-check' | 'permission-gated' | 'external'
  executionMode?: ToolExecutionMode
  renderKind?: ToolRenderKind
  renderShell?: ToolRenderShell
  // Tool category for grouping in UI
  category: 'builtin' | 'custom'
  // Icon for UI display
  icon?: string
  // Tool source for UI display
  source?: 'builtin' | 'plugin' | 'mcp'  // Where the tool comes from
  serverId?: string           // MCP server ID (only for MCP tools)
  serverName?: string         // MCP server name (only for MCP tools)
}

export interface ToolResultContentPart {
  type: 'text' | 'image' | 'file'
  text?: string
  data?: string
  mimeType?: string
  path?: string
}

export interface ToolResult<TDetails = JsonObject | undefined> {
  content: ToolResultContentPart[]
  details?: TDetails
  terminate?: boolean
}

export type ToolPartialResult<TDetails = JsonObject | undefined> = ToolResult<TDetails>

export type ToolExecutionMode = 'parallel' | 'sequential'
export type ToolRenderShell = 'default' | 'self'
export type ToolRenderKind = 'text' | 'bash' | 'diff' | 'file' | 'search' | 'image' | 'custom'

/**
 * One line of a structured diff hunk. Unified-diff text is ambiguous (a
 * deleted line starting with `--` reads as a `---` file header), so display
 * consumers use these explicit ops instead of re-parsing patch text.
 */
export interface DiffHunkLine {
  op: 'ctx' | 'add' | 'del' | 'noeof'
  text: string
}

export interface DiffHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  lines: DiffHunkLine[]
}

export interface ToolCall {
  id: string                 // Unique ID for this tool call
  toolId: string             // ID of the tool being called
  toolName: string           // Name of the tool
  arguments: JsonObject      // Arguments passed to the tool
  status: 'pending' | 'queued' | 'received' | 'executing' | 'completed' | 'failed' | 'cancelled' | 'input-streaming'
  result?: JsonValue         // Result of the tool execution
  error?: string             // Error message if failed
  rejected?: boolean         // True when the user rejected permission for this call
  rejectionReason?: string   // Optional user-provided rejection reason
  timestamp: number
  receivedAt?: number        // When the argument stream finished (tool:input-end), before execution
  argsFinalizedBy?: 'parse' | 'provider-done'  // How streamed args were finalized ('parse' = mid-stream JSON completion)
  startTime?: number         // Execution start timestamp (Date.now, integer ms)
  endTime?: number           // Execution end timestamp (Date.now, integer ms)
  durationMs?: number        // Authoritative execution duration measured in the main process
  // For dangerous commands that need user confirmation
  requiresConfirmation?: boolean
  commandType?: 'read-only' | 'dangerous' | 'forbidden'
  // For edit tool: diff preview (displayed instead of arguments)
  changes?: {
    diff: string
    /** Structured hunks; render from these, never by re-parsing `diff` text. */
    hunks?: DiffHunk[]
    filePath: string
    additions: number
    deletions: number
    /** @deprecated Rollback goes through auditPath; only legacy persisted sessions still carry this. */
    originalContent?: string
    originalContentHash?: string
    afterContentHash?: string
    auditId?: string
    auditPath?: string
  }
  // For streaming tool input
  // Shows partial args JSON as it's being generated by the model
  streamingArgs?: string
  // Pending permission request fields (set when permission:request fires)
  permissionId?: string       // ID of the pending permission request
  canRespond?: boolean        // Whether this UI can respond (vs read-only mirror)
  // Waiting behind another prompt in the session's serialized permission
  // queue (permission:queued fired, no card yet)
  permissionQueued?: boolean
}

// Bash tool specific settings
export interface BashToolSettings {
  enableSandbox: boolean              // Whether to enable directory sandbox
  defaultWorkingDirectory?: string    // Default working directory for commands
  allowedDirectories: string[]        // List of allowed directories
  confirmDangerousCommands: boolean   // Whether to confirm dangerous commands
  dangerousCommandWhitelist: string[] // Commands to skip confirmation (e.g., "npm install")
  /**
   * Environment variables bash may see, on top of the baseline a shell needs
   * (PATH/HOME/TERM/locale — see getShellEnv). Entries may end in `*` to take a
   * family, e.g. `npm_config_*`.
   *
   * `null` (the default) inherits `process.env` wholesale, which on desktop
   * carries everything the user's login shell exported — API keys included.
   * Set a list to close that off; expect to name whatever your toolchains need
   * (GH_TOKEN, HTTPS_PROXY, language-specific vars).
   */
  envAllowlist?: string[] | null
}

// Web Search settings
export interface WebSearchSettings {
  enabled: boolean                // Master switch for web search
  braveApiKey?: string            // Brave Search API key
  defaultProvider?: 'brave'       // Default search provider (extensible)
  defaultCount?: number           // Default number of results (1-10)
}

export type PermissionMode = 'normal' | 'auto-accept-edits' | 'dangerously-allow-all'

export interface ToolCallModelSettings {
  /** Provider used for lightweight AI utility calls, memory background tasks, and dreaming. Empty = use chat default. */
  providerId?: string
  /** Model used for lightweight AI utility calls, memory background tasks, and dreaming. Empty = provider default model. */
  model?: string
  /** Independent thinking toggle for lightweight AI utility calls. Defaults to disabled. */
  thinking?: boolean
  /** Thinking effort used only when lightweight utility thinking is enabled. */
  thinkingEffort?: ThinkingEffort
}

export interface ToolSettings {
  // Global tool settings
  enableToolCalls: boolean   // Master switch for tool calls
  permissionMode?: PermissionMode // Session/runtime permission mode (global default for now)
  toolCallModel?: ToolCallModelSettings
  /**
   * 「接入目录」——用户在设置里亲手加的绝对路径清单。加入即五件套全开:
   * 可被 @ 引用、被搜索、**直接编辑(免逐次确认)**、其中的 SKILL.md 被自动
   * 发现,markdown 附件也认这些根。
   *
   * 第三条是权限面语义,不是便利开关:这些目录进入**可写沙箱根**
   * (`getCoreSandboxRoots`),于是 write/edit 的 effect 不再标 `external`,
   * `auto-accept-edits` 模式下就不弹卡(`core/permission/permission-policy.ts:146`)。
   * 所以只有用户显式添加的目录能进来 —— 默认空列表,行为与没有这个功能时逐字节一致。
   */
  connectedDirectories?: string[]
  // Per-tool settings (toolId -> settings)
  tools: Record<string, {
    enabled: boolean
    autoExecute: boolean
  }>
  // Bash tool specific settings
  bash?: BashToolSettings
  // Web Search settings
  webSearch?: WebSearchSettings
}

// Stream message types
export interface StreamMessageChunk {
  type: 'text' | 'reasoning' | 'error' | 'complete' | 'tool_call' | 'tool_result'
  content: string
  messageId?: string
  reasoning?: string
  toolCall?: ToolCall
}

export interface SendMessageStreamResponse {
  success: boolean
  chunk?: StreamMessageChunk
  error?: string
  errorDetails?: string
}

// ============================================
// Router
// ============================================

/**
 * tools(工具面)域 —— 结构债 P4c 第九批,数据面整只从手写 IPC 通道迁到
 * 通用 `rpc:invoke` / `POST /api/rpc`。
 *
 * 迁来时是七条,逐条对应从前 `IPC_CHANNELS` 上那七条 `tools:*` 通道(`GET_TOOLS` /
 * `EXECUTE_TOOL` / `CANCEL_TOOL` / `BACKGROUND_JOBS_LIST` / `BACKGROUND_JOBS_STOP` /
 * `REFRESH_ASYNC_TOOLS` / `UPDATE_TOOL_CALL`),请求/响应形状一字未改;变的只是通道。
 * 今天只剩六条:`refreshAsyncTools` 全仓零调用点(bridge 从未暴露它),P4-F #34 退役 ——
 * 刷 MCP 工具面的那件事本身还在,只是没有传输面(`backend/wiring/toolkit` 的
 * `refreshToolkitMcpTools`,由 `createOnethingBackend` 挂在 MCP 能力变更回调上)。
 *
 * 位置参数在这里被收成**单 id 包对象**(本仓 router 惯例):`executeTool` 从前是
 * `(toolId, args, messageId, sessionId)` 四个位置参数、`updateToolCall` 是四个,
 * 现在各是一个请求对象 —— 渲染侧客户端保留旧的位置参数签名,调用点因此零改动。
 *
 * 无参的 `getTools` 按惯例递 `{}`。
 */
import { defineRouter } from './router.js'

export interface CancelToolRequest {
  toolCallId: string
  /** Disambiguates providers which reuse call IDs in different sessions. */
  sessionId?: string
}

export interface CancelToolResponse {
  success: boolean
}

export interface BackgroundJobsListRequest {
  includeInactive?: boolean
}

export interface BackgroundJobsListResponse {
  success: boolean
  /**
   * 后台任务的形状住在产品层(`runtime/src/tools/background-jobs.ts` 的
   * `BackgroundJob`),契约层不抄第二份 —— 两个消费者都是就地 `as` 成自己的视图
   * 类型,与迁移前 `jobs?: Array<Record<string, any>>` 那一格同义。
   */
  jobs?: unknown[]
  error?: string
}

export interface BackgroundJobsStopRequest {
  jobId: string
}

export interface BackgroundJobsStopResponse {
  success: boolean
  error?: string
}

export interface UpdateToolCallRequest {
  sessionId: string
  messageId: string
  toolCallId: string
  updates: Partial<ToolCall>
}

export interface UpdateToolCallResponse {
  success: boolean
  error?: string
}

export type ToolsRoutes = {
  getTools: { input: Record<string, never>; output: GetToolsResponse }
  executeTool: { input: ExecuteToolRequest; output: ExecuteToolResponse }
  cancelTool: { input: CancelToolRequest; output: CancelToolResponse }
  backgroundJobsList: {
    input: BackgroundJobsListRequest
    output: BackgroundJobsListResponse
  }
  backgroundJobsStop: {
    input: BackgroundJobsStopRequest
    output: BackgroundJobsStopResponse
  }
  updateToolCall: { input: UpdateToolCallRequest; output: UpdateToolCallResponse }
}

export const toolsRouter = defineRouter<ToolsRoutes>('tools', [
  'getTools',
  'executeTool',
  'cancelTool',
  'backgroundJobsList',
  'backgroundJobsStop',
  'updateToolCall',
])
