/**
 * Collab v3 的 actor 面(`@onething/runtime/collab/actors`)。
 *
 * 这里是**协议**、**验收架**与**纯规则**:动词表(D0)、金重放架(D0)、
 * 房间的账与三道闸(D1 `room-rules.ts`)、发言策略族(D1 `floor-policy.ts`)、
 * agent 的账与举手/drive 组装(D2 `mind-rules.ts`)、mailbox 折叠信封(D2
 * `envelope-fold.ts`)、跨房笔记(D2 `notebook-rules.ts`)。
 * 带 IO 的那一半(落盘、mailbox、宿主端口)在 `@onething/backend` 的
 * `collab/actors/`。设计:docs/design/collab-actor-v3.md。
 */
export {
  COLLAB_ACTOR_VERB_TABLE_IS_EXHAUSTIVE,
  COLLAB_ACTOR_VERB_TYPES,
  collabActorRef,
  collabActorVerbDirection,
  collabActorVerbSender,
  collabAgentDmOpen,
  collabAgentNote,
  collabAgentRaiseHand,
  collabAgentSpawnWorker,
  collabAgentSpeak,
  collabAgentWake,
  collabAgentWorkerResult,
  collabAgentYield,
  collabRefereeSetFloorPolicy,
  collabRoomCardEvent,
  collabRoomFloorGranted,
  collabRoomFloorRevoked,
  collabRoomMembershipChanged,
  collabRoomPhaseChanged,
  collabRoomPosted,
  isCollabActorVerbType,
} from './protocol.js'
export type {
  CollabActorKind,
  CollabActorRef,
  CollabActorVerb,
  CollabActorVerbDirection,
  CollabActorVerbType,
  CollabAgentDmOpenVerb,
  CollabAgentNoteVerb,
  CollabAgentRaiseHandVerb,
  CollabAgentSpawnWorkerVerb,
  CollabAgentSpeakVerb,
  CollabAgentWakeVerb,
  CollabAgentWorkerResultVerb,
  CollabAgentYieldVerb,
  CollabCardEventKind,
  CollabFloorPolicyName,
  CollabFloorPolicyParams,
  CollabFloorRevokeReason,
  CollabHandUrgency,
  CollabRefereeSetFloorPolicyVerb,
  CollabRoomCardEventVerb,
  CollabRoomFloorGrantedVerb,
  CollabRoomFloorRevokedVerb,
  CollabRoomMembershipChangedVerb,
  CollabRoomPhaseChangedVerb,
  CollabRoomPostedVerb,
  CollabWorkerEvidenceRef,
  CollabWorkerOutcome,
  CollabYieldReason,
} from './protocol.js'

export {
  COLLAB_REPLAY_EVENT_ID_PREFIX,
  createCollabActorPassthroughPipeline,
  formatCollabActorReplay,
  formatCollabActorVerb,
  orderTranscriptMessages,
  parseRoomTranscriptJsonl,
  replayMessageAuthor,
  replayRoomTranscript,
  transcriptMessageKey,
} from './replay.js'
export type {
  CollabActorPassthroughPipeline,
  CollabActorReplayContext,
  CollabActorReplayOptions,
  CollabActorReplayPipeline,
  CollabActorReplayResult,
  CollabActorReplayTranscript,
} from './replay.js'

export {
  collabFloorSeats,
  createCollabFreeFloorPolicy,
  createCollabPhaseFloorPolicy,
  createCollabRingFloorPolicy,
  createCollabWavesFloorPolicy,
  isSameCollabRoomFloorPolicy,
  orderCollabHands,
  resolveCollabFloorPolicy,
  resolveCollabRoomFloorPolicy,
} from './floor-policy.js'
export type {
  CollabFloorDecision,
  CollabFloorDecisionInput,
  CollabFloorGrantCandidate,
  CollabFloorPolicy,
  CollabFloorPolicyState,
  CollabRaisedHand,
  CollabResolvedFloorPolicy,
} from './floor-policy.js'

/* ── D3:Referee ────────────────────────────────────────────────────────── */

export {
  buildCollabRefereeJudgePrompt,
  COLLAB_REFEREE_MAX_GRANTS,
  COLLAB_REFEREE_RECENT_LIMIT,
  COLLAB_REFEREE_SYSTEM,
  COLLAB_REFEREE_WHY_LIMIT,
  collabJudgmentToken,
  collabRefereeVerdictVerb,
  isCollabRoomJudgmentShape,
  parseCollabRefereeVerdict,
} from './referee-rules.js'
export type {
  BuildCollabRefereeJudgePromptOptions,
  CollabRefereeJudgePrompt,
  CollabRefereeVerdict,
  CollabRoomJudgment,
  CollabRoomJudgmentRequest,
  CollabRoomJudgmentState,
  ParseCollabRefereeVerdictOptions,
} from './referee-rules.js'

export {
  applyCollabRoomPassthrough,
  applyCollabRoomPhaseChange,
  applyCollabRoomPosted,
  applyCollabRoomRaiseHand,
  applyCollabRoomSetPolicy,
  applyCollabRoomSpeak,
  applyCollabRoomYield,
  buildCollabRoomBudgetHoldLine,
  bumpCollabRoomEpoch,
  COLLAB_ROOM_ACCOUNT_VERSION,
  COLLAB_ROOM_DEFAULT_FLOOR_POLICY,
  COLLAB_ROOM_FROZEN_LINE,
  COLLAB_ROOM_FROZEN_LINE_DM,
  COLLAB_SPEAK_REFUSED_EXPIRED_LEASE,
  COLLAB_SPEAK_REFUSED_LEASE_OWNER,
  COLLAB_SPEAK_REFUSED_NO_LEASE,
  COLLAB_SPEAK_REFUSED_STALE_LEASE,
  collabRoomActiveLeases,
  collabRoomChainEntryOf,
  collabRoomEventId,
  collabRoomHolders,
  createCollabRoomAccount,
  enqueueCollabHand,
  foldCollabRoomChain,
  normalizeCollabRoomAccount,
  openCollabRoomBroadcast,
  pruneCollabRoomFloor,
  resolveCollabRoomHandBlock,
  revokeCollabRoomLease,
  settleCollabRoomBroadcast,
} from './room-rules.js'
export type {
  CollabRoomAccount,
  CollabRoomChainEntry,
  CollabRoomHandBlock,
  CollabRoomEffects,
  CollabRoomGates,
  CollabRoomIdSource,
  CollabRoomPendingBroadcast,
  CollabRoomStep,
  CollabRoomTranscriptMessage,
} from './room-rules.js'

export {
  buildCollabFoldedEnvelope,
  COLLAB_FOLD_ROOM_FALLBACK_LABEL,
  COLLAB_FOLD_SELF_BUCKET,
  COLLAB_FOLD_SPEAKER_FALLBACK_LABEL,
  COLLAB_FOLD_USER_LABEL,
  mergeCollabFoldEntries,
} from './envelope-fold.js'
export type {
  BuildCollabFoldedEnvelopeOptions,
  CollabFoldCardEntry,
  CollabFoldEntry,
  CollabFoldGotEntry,
  CollabFoldMembersEntry,
  CollabFoldPhaseEntry,
  CollabFoldWorkerEntry,
} from './envelope-fold.js'

export {
  buildCollabNotebookBlock,
  clipCollabNotebookTail,
  COLLAB_NOTEBOOK_ENTRY_CLIPPED_SUFFIX,
  COLLAB_NOTEBOOK_ENTRY_MAX_CHARS,
  COLLAB_NOTEBOOK_INJECT_MAX_CHARS,
  COLLAB_NOTEBOOK_TAG,
  COLLAB_NOTEBOOK_TRUNCATED_LINE,
  formatCollabNotebookEntry,
  formatCollabNotebookTime,
} from './notebook-rules.js'
export type {
  BuildCollabNotebookBlockOptions,
  CollabNotebookTail,
  FormatCollabNotebookEntryOptions,
} from './notebook-rules.js'

export {
  adoptCollabAgentWorkerOrphans,
  advanceCollabAgentDelivered,
  advanceCollabAgentRead,
  buildCollabMindDrive,
  clearCollabAgentHand,
  COLLAB_AGENT_ACCOUNT_VERSION,
  COLLAB_AGENT_FOLD_BUFFER_MAX,
  COLLAB_AGENT_FOLD_SEEN_MAX,
  COLLAB_HAND_NOT_RAISED,
  collabAgentLeaseOf,
  collabAgentRoomAccount,
  collabPostedSpeakerId,
  createCollabAgentAccount,
  createCollabHeuristicHandEvaluator,
  dropCollabAgentLease,
  normalizeCollabAgentAccount,
  pushCollabAgentFold,
  raiseCollabAgentHand,
  recordCollabAgentLease,
  recordCollabAgentTurn,
  recordCollabAgentWorkerResult,
  settleCollabAgentWorker,
  startCollabAgentWorker,
  takeCollabAgentFold,
} from './mind-rules.js'
export {
  adoptCollabWorkerOrphans,
  admitCollabWorker,
  buildCollabWorkerBriefing,
  buildCollabWorkerFoldEntry,
  COLLAB_WORKER_DELIVERABLE_PATH_KEYS,
  COLLAB_WORKER_DELIVERABLE_TOOLS,
  COLLAB_WORKER_EVIDENCE_EXCLUDED_TOOLS,
  COLLAB_WORKER_EVIDENCE_MAX_REFS,
  COLLAB_WORKER_EVIDENCE_REF_MAX_CHARS,
  COLLAB_WORKER_MAX_GLOBAL,
  COLLAB_WORKER_MAX_PER_AGENT,
  COLLAB_WORKER_ROSTER_MAX,
  COLLAB_WORKER_START_TIMEOUT_MS,
  COLLAB_WORKER_SUMMARY_MAX_CHARS,
  COLLAB_WORKER_WALL_CLOCK_MS,
  collabWorkerOf,
  collabWorkerOutcomeOk,
  collabWorkerRunning,
  collabWorkerRunningForCard,
  collectCollabWorkerEvidence,
  createCollabWorkerRecord,
  normalizeCollabAgentWorkerRecords,
  pruneCollabWorkerRecords,
  settleCollabWorkerRecord,
  truncateCollabWorkerSummary,
  upsertCollabWorkerRecord,
} from './worker-rules.js'
export type {
  BuildCollabWorkerBriefingOptions,
  CollabAgentWorkerRecord,
  CollabWorkerAdmission,
  CollabWorkerAdmissionReason,
  CollabWorkerLimits,
  CollabWorkerOrphanAdoption,
  CollabWorkerStatus,
  CollabWorkerToolCallLike,
} from './worker-rules.js'

export type {
  BuildCollabMindDriveOptions,
  CollabAgentAccount,
  CollabAgentFoldTake,
  CollabAgentLeaseRecord,
  CollabAgentRoomAccount,
  CollabHandEvaluation,
  CollabHandEvaluationInput,
  CollabHandEvaluator,
} from './mind-rules.js'

/* ── D5:v2 → v3 迁移的纯规则 ───────────────────────────────────────────── */

export {
  COLLAB_MIGRATION_BACKFILL_MAX,
  COLLAB_V2_BACKUP_DIR_PREFIX,
  COLLAB_V3_MIGRATION_MARKER_FILE,
  COLLAB_V3_MIGRATION_VERSION,
  formatCollabMigrationReport,
  planCollabAgentRoomMigration,
  planCollabRoomAccountMigration,
  readCollabV2RoomState,
  summarizeCollabMigration,
} from './migrate-rules.js'
export type {
  CollabAgentRoomMigrationPlan,
  CollabAgentRoomMigrationSummary,
  CollabMigrationCheck,
  CollabMigrationCheckStatus,
  CollabMigrationRecipients,
  CollabMigrationTotals,
  CollabRoomMigrationEntry,
  CollabRoomMigrationPlan,
  CollabRoomMigrationStatus,
  CollabRoomMigrationSummary,
  CollabV2RoomStateView,
  CollabV3MigrationMarker,
  CollabV3MigrationReport,
} from './migrate-rules.js'

/* ── D8:调度时间轴的纯规则 ─────────────────────────────────────────────── */

export {
  COLLAB_SCHEDULER_ERROR_LINE_MAX,
  COLLAB_SCHEDULER_LOG_CARRIES_NO_TRANSCRIPT,
  COLLAB_SCHEDULER_LOG_FILE_PREFIX,
  COLLAB_SCHEDULER_LOG_FILE_SUFFIX,
  COLLAB_SCHEDULER_LOG_RETENTION_DAYS,
  COLLAB_SCHEDULER_LOG_TABLE_IS_EXHAUSTIVE,
  COLLAB_SCHEDULER_LOG_TYPES,
  collabSchedulerCauseId,
  collabSchedulerDeadLetter,
  collabSchedulerErrorLine,
  collabSchedulerExternalTool,
  collabSchedulerExternalTurn,
  collabSchedulerGateBlock,
  collabSchedulerGrant,
  collabSchedulerHand,
  collabSchedulerInteraction,
  collabSchedulerJudgeDegraded,
  collabSchedulerJudgeOpen,
  collabSchedulerJudgeVerdict,
  collabSchedulerLogDayKey,
  collabSchedulerLogFileDayKey,
  collabSchedulerLogFileName,
  collabSchedulerPhase,
  collabSchedulerPosted,
  collabSchedulerRevoke,
  collabSchedulerSpeak,
  collabSchedulerWorkerResult,
  collabSchedulerWorkerSpawn,
  collabSchedulerYield,
  deriveCollabSchedulerLogRows,
  formatCollabSchedulerLogLine,
  isCollabSchedulerLogExpired,
  isCollabSchedulerLogType,
  parseCollabSchedulerLogLine,
} from './scheduler-log-rules.js'
export type {
  CollabExternalTurnOutcome,
  CollabSchedulerBlockLatch,
  CollabSchedulerDeadLetterRow,
  CollabSchedulerExternalToolRow,
  CollabSchedulerExternalTurnRow,
  CollabSchedulerGateBlockRow,
  CollabSchedulerGrantRow,
  CollabSchedulerHandRow,
  CollabSchedulerInteractionPhase,
  CollabSchedulerInteractionRow,
  CollabSchedulerJudgeDegradedRow,
  CollabSchedulerJudgeOpenRow,
  CollabSchedulerJudgeVerdictRow,
  CollabSchedulerLogBase,
  CollabSchedulerLogRow,
  CollabSchedulerLogSink,
  CollabSchedulerLogType,
  CollabSchedulerPhaseRow,
  CollabSchedulerPostedRow,
  CollabSchedulerRevokeRow,
  CollabSchedulerRoomStepInput,
  CollabSchedulerSpeakRow,
  CollabSchedulerWorkerResultRow,
  CollabSchedulerWorkerSpawnRow,
  CollabSchedulerYieldRow,
} from './scheduler-log-rules.js'
