/**
 * The single source of truth for @onething/* module resolution.
 *
 * package.json "exports" maps are dead here (no npm workspaces — everything
 * resolves from source via these aliases), and four configs used to carry
 * hand-synced copies of this table (electron-vite, vitest, apps/server,
 * apps/web). Missing an entry fails only at build/run time, never at
 * typecheck (tsconfig wildcards accept any subpath) — so keep exactly one
 * table and spread it everywhere.
 *
 * Ordering matters: string finds are prefix matchers, first match wins —
 * keep longer prefixes before their shorter siblings within each family.
 */
import { resolve } from 'node:path'

export interface OnethingAliasEntry {
  find: string | RegExp
  replacement: string
}

export function onethingPackageAliases(projectRoot: string): OnethingAliasEntry[] {
  return [
  // Product assembly tree (the former apps/electron/src/main). One prefix
  // entry covers every subpath — do NOT add per-file entries for it.
  { find: '@onething/app', replacement: resolve(projectRoot, 'packages/onething-runtime/src/app') },
  { find: '@onething/core/actors', replacement: resolve(projectRoot, 'packages/core/actors/index.ts') },
  { find: '@onething/core/agent-loop', replacement: resolve(projectRoot, 'packages/core/agent-loop/index.ts') },
  // Browser-safe leaf module (no node deps) — must be registered BEFORE the
  // engine barrel so the renderer never drags node:crypto into the bundle.
  { find: '@onething/core/engine/attachment-mime', replacement: resolve(projectRoot, 'packages/core/engine/attachment-mime.ts') },
  { find: '@onething/core/engine/streaming-args', replacement: resolve(projectRoot, 'packages/core/engine/streaming-args.ts') },
  { find: '@onething/core/engine', replacement: resolve(projectRoot, 'packages/core/engine/index.ts') },
  { find: '@onething/core/events', replacement: resolve(projectRoot, 'packages/core/events/index.ts') },
  { find: '@onething/core/gateway-runtime', replacement: resolve(projectRoot, 'packages/core/gateway-runtime.ts') },
  { find: '@onething/core/http', replacement: resolve(projectRoot, 'packages/core/http/index.ts') },
  { find: '@onething/core/interaction', replacement: resolve(projectRoot, 'packages/core/interaction/index.ts') },
  { find: '@onething/core/ipc', replacement: resolve(projectRoot, 'packages/core/ipc/index.ts') },
  { find: '@onething/core/json', replacement: resolve(projectRoot, 'packages/core/json.ts') },
  { find: '@onething/core/mcp', replacement: resolve(projectRoot, 'packages/core/mcp/index.ts') },
  { find: '@onething/core/permission', replacement: resolve(projectRoot, 'packages/core/permission/index.ts') },
  // Browser-safe leaf module (zero imports, pure serialization logic) — must be
  // registered BEFORE the plugins barrel so the renderer never drags loader.ts
  // (node:url 的 pathToFileURL) into the bundle;桶一进浏览器包就在求值时炸。
  { find: '@onething/core/plugins/request-channel', replacement: resolve(projectRoot, 'packages/core/plugins/request-channel.ts') },
  // Same reason as request-channel: a zero-import leaf (N1 的会话动词协议:枚举 +
  // 常量 + 纯函数),披露文案要在设置页复用同一份口径,所以它必须排在桶前面。
  { find: '@onething/core/plugins/sessions', replacement: resolve(projectRoot, 'packages/core/plugins/sessions.ts') },
  // 同理的第三片叶子(M1 通知音效集):枚举 + 常量 + 纯函数,零 import。
  // 音效名的事实源要被 renderer 的合成配方表引用(exhaustive Record),所以它
  // 必须排在桶前面 —— 走桶会把 loader.ts 拖进浏览器包。
  { find: '@onething/core/plugins/notify-sound', replacement: resolve(projectRoot, 'packages/core/plugins/notify-sound.ts') },
  // 第四片叶子(H4 深链协议):枚举 + 常量 + 纯解析函数,零 import。确认卡要在
  // renderer 侧复用同一份口径(长度上限、可见拒绝),所以它必须排在桶前面。
  { find: '@onething/core/plugins/deep-link', replacement: resolve(projectRoot, 'packages/core/plugins/deep-link.ts') },
  { find: '@onething/core/plugins', replacement: resolve(projectRoot, 'packages/core/plugins/index.ts') },
  { find: '@onething/core/session/storage', replacement: resolve(projectRoot, 'packages/core/session/storage/index.ts') },
  { find: '@onething/core/session', replacement: resolve(projectRoot, 'packages/core/session/index.ts') },
  { find: '@onething/core/slash-commands', replacement: resolve(projectRoot, 'packages/core/slash-commands.ts') },
  { find: '@onething/core/storage', replacement: resolve(projectRoot, 'packages/core/storage/index.ts') },
  { find: '@onething/core/tools', replacement: resolve(projectRoot, 'packages/core/tools/index.ts') },
  { find: '@onething/core', replacement: resolve(projectRoot, 'packages/core/index.ts') },
  { find: '@onething/gateway/config', replacement: resolve(projectRoot, 'packages/gateway/src/config.ts') },
  { find: '@onething/gateway/core', replacement: resolve(projectRoot, 'packages/gateway/src/core/index.ts') },
  { find: '@onething/gateway/telegram', replacement: resolve(projectRoot, 'packages/gateway/src/channels/telegram/index.ts') },
  { find: '@onething/gateway/wechat', replacement: resolve(projectRoot, 'packages/gateway/src/channels/wechat/index.ts') },
  { find: '@onething/gateway', replacement: resolve(projectRoot, 'packages/gateway/src/index.ts') },
  { find: '@onething/electron-host/accessibility/permissions', replacement: resolve(projectRoot, 'apps/electron/src/accessibility/permissions.ts') },
  { find: '@onething/electron-host/app/activate', replacement: resolve(projectRoot, 'apps/electron/src/app/activate.ts') },
  { find: '@onething/electron-host/app/before-quit', replacement: resolve(projectRoot, 'apps/electron/src/app/before-quit.ts') },
  { find: '@onething/electron-host/app/bootstrap', replacement: resolve(projectRoot, 'apps/electron/src/app/bootstrap.ts') },
  { find: '@onething/electron-host/app/did-become-active', replacement: resolve(projectRoot, 'apps/electron/src/app/did-become-active.ts') },
  { find: '@onething/electron-host/app/login-shell-env', replacement: resolve(projectRoot, 'apps/electron/src/app/login-shell-env.ts') },
  { find: '@onething/electron-host/app/main-process', replacement: resolve(projectRoot, 'apps/electron/src/app/main-process.ts') },
  { find: '@onething/electron-host/app/ready', replacement: resolve(projectRoot, 'apps/electron/src/app/ready.ts') },
  { find: '@onething/electron-host/app/window-all-closed', replacement: resolve(projectRoot, 'apps/electron/src/app/window-all-closed.ts') },
  { find: '@onething/electron-host/auth/auth-fetch', replacement: resolve(projectRoot, 'apps/electron/src/auth/auth-fetch.ts') },
  { find: '@onething/electron-host/auth/electron-auth', replacement: resolve(projectRoot, 'apps/electron/src/auth/electron-auth.ts') },
  { find: '@onething/electron-host/auth/token-store', replacement: resolve(projectRoot, 'apps/electron/src/auth/token-store.ts') },
  { find: '@onething/electron-host/browser/chromium-flags', replacement: resolve(projectRoot, 'apps/electron/src/browser/chromium-flags.ts') },
  { find: '@onething/electron-host/browser/service', replacement: resolve(projectRoot, 'apps/electron/src/browser/service.ts') },
  { find: '@onething/electron-host/browser/session', replacement: resolve(projectRoot, 'apps/electron/src/browser/session.ts') },
  { find: '@onething/electron-host/browser/tab-state', replacement: resolve(projectRoot, 'apps/electron/src/browser/tab-state.ts') },
  { find: '@onething/electron-host/deeplink/protocol', replacement: resolve(projectRoot, 'apps/electron/src/deeplink/protocol.ts') },
  { find: '@onething/electron-host/deeplink/service', replacement: resolve(projectRoot, 'apps/electron/src/deeplink/service.ts') },
  { find: '@onething/electron-host/gateway/lifecycle', replacement: resolve(projectRoot, 'apps/electron/src/gateway/lifecycle.ts') },
  { find: '@onething/electron-host/ipc/acp', replacement: resolve(projectRoot, 'apps/electron/src/ipc/acp.ts') },
  { find: '@onething/electron-host/ipc/app-state', replacement: resolve(projectRoot, 'apps/electron/src/ipc/app-state.ts') },
  { find: '@onething/electron-host/ipc/browser', replacement: resolve(projectRoot, 'apps/electron/src/ipc/browser.ts') },
  { find: '@onething/electron-host/ipc/chat', replacement: resolve(projectRoot, 'apps/electron/src/ipc/chat.ts') },
  { find: '@onething/electron-host/ipc/files', replacement: resolve(projectRoot, 'apps/electron/src/ipc/files.ts') },
  { find: '@onething/electron-host/ipc/gateway', replacement: resolve(projectRoot, 'apps/electron/src/ipc/gateway.ts') },
  { find: '@onething/electron-host/ipc/interaction', replacement: resolve(projectRoot, 'apps/electron/src/ipc/interaction.ts') },
  { find: '@onething/electron-host/ipc/media', replacement: resolve(projectRoot, 'apps/electron/src/ipc/media.ts') },
  { find: '@onething/electron-host/ipc/mcp', replacement: resolve(projectRoot, 'apps/electron/src/ipc/mcp.ts') },
  { find: '@onething/electron-host/ipc/oauth', replacement: resolve(projectRoot, 'apps/electron/src/ipc/oauth.ts') },
  { find: '@onething/electron-host/ipc/permission', replacement: resolve(projectRoot, 'apps/electron/src/ipc/permission.ts') },
  { find: '@onething/electron-host/ipc/plugins', replacement: resolve(projectRoot, 'apps/electron/src/ipc/plugins.ts') },
  { find: '@onething/electron-host/ipc/project-dirs', replacement: resolve(projectRoot, 'apps/electron/src/ipc/project-dirs.ts') },
  { find: '@onething/electron-host/ipc/scheduler', replacement: resolve(projectRoot, 'apps/electron/src/ipc/scheduler.ts') },
  { find: '@onething/electron-host/ipc/scratchpad', replacement: resolve(projectRoot, 'apps/electron/src/ipc/scratchpad.ts') },
  { find: '@onething/electron-host/ipc/shell', replacement: resolve(projectRoot, 'apps/electron/src/ipc/shell.ts') },
  { find: '@onething/electron-host/ipc/session-command', replacement: resolve(projectRoot, 'apps/electron/src/ipc/session-command.ts') },
  { find: '@onething/electron-host/ipc/sessions', replacement: resolve(projectRoot, 'apps/electron/src/ipc/sessions.ts') },
  { find: '@onething/electron-host/ipc/skills', replacement: resolve(projectRoot, 'apps/electron/src/ipc/skills.ts') },
  { find: '@onething/electron-host/ipc/spaces', replacement: resolve(projectRoot, 'apps/electron/src/ipc/spaces.ts') },
  { find: '@onething/electron-host/ipc/terminal', replacement: resolve(projectRoot, 'apps/electron/src/ipc/terminal.ts') },
  { find: '@onething/electron-host/ipc/themes', replacement: resolve(projectRoot, 'apps/electron/src/ipc/themes.ts') },
  { find: '@onething/electron-host/ipc/todo-plan', replacement: resolve(projectRoot, 'apps/electron/src/ipc/todo-plan.ts') },
  { find: '@onething/electron-host/ipc/tools', replacement: resolve(projectRoot, 'apps/electron/src/ipc/tools.ts') },
  { find: '@onething/electron-host/ipc/window', replacement: resolve(projectRoot, 'apps/electron/src/ipc/window.ts') },
  { find: '@onething/electron-host/ipc/variables', replacement: resolve(projectRoot, 'apps/electron/src/ipc/variables.ts') },
  { find: '@onething/electron-host/logging/console-capture', replacement: resolve(projectRoot, 'apps/electron/src/logging/console-capture.ts') },
  { find: '@onething/electron-host/menu/application-menu', replacement: resolve(projectRoot, 'apps/electron/src/menu/application-menu.ts') },
  { find: '@onething/electron-host/web-preview/web-preview', replacement: resolve(projectRoot, 'apps/electron/src/web-preview/web-preview.ts') },
  { find: '@onething/electron-host/media/protocol', replacement: resolve(projectRoot, 'apps/electron/src/media/protocol.ts') },
  { find: '@onething/electron-host/network/proxy', replacement: resolve(projectRoot, 'apps/electron/src/network/proxy.ts') },
  { find: '@onething/electron-host/oauth/events', replacement: resolve(projectRoot, 'apps/electron/src/oauth/events.ts') },
  { find: '@onething/electron-host/plugins/file-pick', replacement: resolve(projectRoot, 'apps/electron/src/plugins/file-pick.ts') },
  { find: '@onething/electron-host/power/resume', replacement: resolve(projectRoot, 'apps/electron/src/power/resume.ts') },
  { find: '@onething/electron-host/search/ipc', replacement: resolve(projectRoot, 'apps/electron/src/search/ipc.ts') },
  { find: '@onething/electron-host/search/window-actions', replacement: resolve(projectRoot, 'apps/electron/src/search/window-actions.ts') },
  { find: '@onething/electron-host/search/window-controller', replacement: resolve(projectRoot, 'apps/electron/src/search/window-controller.ts') },
  { find: '@onething/electron-host/search/window', replacement: resolve(projectRoot, 'apps/electron/src/search/window.ts') },
  { find: '@onething/electron-host/settings/ipc-host', replacement: resolve(projectRoot, 'apps/electron/src/settings/ipc-host.ts') },
  { find: '@onething/electron-host/shell/operations', replacement: resolve(projectRoot, 'apps/electron/src/shell/operations.ts') },
  { find: '@onething/electron-host/skills/environment', replacement: resolve(projectRoot, 'apps/electron/src/skills/environment.ts') },
  { find: '@onething/electron-host/shortcuts/global-shortcuts', replacement: resolve(projectRoot, 'apps/electron/src/shortcuts/global-shortcuts.ts') },
  { find: '@onething/electron-host/todo-plan/notifications', replacement: resolve(projectRoot, 'apps/electron/src/todo-plan/notifications.ts') },
  { find: '@onething/electron-host/music/ipc', replacement: resolve(projectRoot, 'apps/electron/src/music/ipc.ts') },
  { find: '@onething/electron-host/voice/events', replacement: resolve(projectRoot, 'apps/electron/src/voice/events.ts') },
  { find: '@onething/electron-host/voice/ipc', replacement: resolve(projectRoot, 'apps/electron/src/voice/ipc.ts') },
  { find: '@onething/electron-host/voice/runtime-window', replacement: resolve(projectRoot, 'apps/electron/src/voice/runtime-window.ts') },
  { find: '@onething/electron-host/voice/tray', replacement: resolve(projectRoot, 'apps/electron/src/voice/tray.ts') },
  { find: '@onething/electron-host/window/activation', replacement: resolve(projectRoot, 'apps/electron/src/window/activation.ts') },
  { find: '@onething/electron-host/window/external-links', replacement: resolve(projectRoot, 'apps/electron/src/window/external-links.ts') },
  { find: '@onething/electron-host/window/image-preview-window', replacement: resolve(projectRoot, 'apps/electron/src/window/image-preview-window.ts') },
  { find: '@onething/electron-host/window/macos-panel', replacement: resolve(projectRoot, 'apps/electron/src/window/macos-panel.ts') },
  { find: '@onething/electron-host/window/main-window', replacement: resolve(projectRoot, 'apps/electron/src/window/main-window.ts') },
  { find: '@onething/electron-host/window/main-window-recovery', replacement: resolve(projectRoot, 'apps/electron/src/window/main-window-recovery.ts') },
  { find: '@onething/electron-host/window/renderer-targets', replacement: resolve(projectRoot, 'apps/electron/src/window/renderer-targets.ts') },
  { find: '@onething/electron-host/window/search-window', replacement: resolve(projectRoot, 'apps/electron/src/window/search-window.ts') },
  { find: '@onething/electron-host/window/search-window-layout', replacement: resolve(projectRoot, 'apps/electron/src/window/search-window-layout.ts') },
  { find: '@onething/electron-host/window/settings-window', replacement: resolve(projectRoot, 'apps/electron/src/window/settings-window.ts') },
  { find: '@onething/electron-host/window/session-security', replacement: resolve(projectRoot, 'apps/electron/src/window/session-security.ts') },
  { find: '@onething/electron-host/window/todo-plan-presentation', replacement: resolve(projectRoot, 'apps/electron/src/window/todo-plan-presentation.ts') },
  { find: '@onething/electron-host/window/todo-plan-window', replacement: resolve(projectRoot, 'apps/electron/src/window/todo-plan-window.ts') },
  { find: '@onething/electron-host/window/types', replacement: resolve(projectRoot, 'apps/electron/src/window/types.ts') },
  { find: '@onething/electron-host/window/window-visibility', replacement: resolve(projectRoot, 'apps/electron/src/window/window-visibility.ts') },
  { find: '@onething/electron-host/window/window-state', replacement: resolve(projectRoot, 'apps/electron/src/window/window-state.ts') },
  { find: '@onething/electron-host/window', replacement: resolve(projectRoot, 'apps/electron/src/window/index.ts') },
  { find: '@onething/runtime/headless', replacement: resolve(projectRoot, 'packages/onething-runtime/src/headless/index.ts') },
  { find: '@onething/runtime/runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/runtime.ts') },
  { find: '@onething/runtime/product-stream-runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/product-stream-runtime.ts') },
  { find: '@onething/runtime/auth', replacement: resolve(projectRoot, 'packages/onething-runtime/src/auth/index.ts') },
  { find: '@onething/runtime/agent-loop/providers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agent-loop/providers/index.ts') },
  { find: '@onething/runtime/agent-loop', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agent-loop/index.ts') },
  { find: '@onething/runtime/stream-runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/stream-runtime.ts') },
  { find: '@onething/runtime/stream-engine', replacement: resolve(projectRoot, 'packages/onething-runtime/src/stream-engine.ts') },
  { find: '@onething/runtime/stream-processor', replacement: resolve(projectRoot, 'packages/onething-runtime/src/stream-processor.ts') },
  { find: '@onething/runtime/gateway', replacement: resolve(projectRoot, 'packages/onething-runtime/src/gateway-runtime.ts') },
  { find: '@onething/runtime/acp', replacement: resolve(projectRoot, 'packages/onething-runtime/src/acp/index.ts') },
  { find: '@onething/runtime/external-agents', replacement: resolve(projectRoot, 'packages/onething-runtime/src/external-agents/index.ts') },
  // Agent 身份/在场的**叶子**入口:renderer 要现算履历(agent-im-dm.md D8)就得
  // 吃 identity/presence 这两支纯函数,而 `agents` 那颗 barrel 拖着吃 node:fs 的
  // store.ts —— 走 barrel 会把文件系统拽进浏览器包。长前缀必须站在短前缀之上
  // (find 是前缀匹配,先命中者赢)。
  { find: '@onething/runtime/agents/identity', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agents/identity.ts') },
  { find: '@onething/runtime/agents/presence', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agents/presence.ts') },
  // 同上第三支:域模型的投影与判定(model.ts)。renderer 吃它是为了墓碑文案的
  // 单一属主(架构审查 B8)—— 它只 `import type` store.ts,类型被擦掉,node:fs
  // 进不了浏览器包。
  { find: '@onething/runtime/agents/model', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agents/model.ts') },
  { find: '@onething/runtime/agents', replacement: resolve(projectRoot, 'packages/onething-runtime/src/agents/index.ts') },
  // Collab v3 的 actor 协议与金重放架。**必须站在 `collab` 之上**:find 是前缀
  // 匹配,先命中者赢 —— 落在下面的话 `…/collab/actors` 会被 `…/collab` 吃掉,
  // 解析成 `collab/index.ts/actors`,而这种错只在 build/run 时才炸(typecheck
  // 的通配符照单全收)。
  { find: '@onething/runtime/collab/actors', replacement: resolve(projectRoot, 'packages/onething-runtime/src/collab/actors/index.ts') },
  { find: '@onething/runtime/collab', replacement: resolve(projectRoot, 'packages/onething-runtime/src/collab/index.ts') },
  { find: '@onething/runtime/files/ripgrep', replacement: resolve(projectRoot, 'packages/onething-runtime/src/files/ripgrep.ts') },
  { find: '@onething/runtime/files', replacement: resolve(projectRoot, 'packages/onething-runtime/src/files/index.ts') },
  { find: '@onething/runtime/mcp', replacement: resolve(projectRoot, 'packages/onething-runtime/src/mcp/index.ts') },
  { find: '@onething/runtime/scheduler', replacement: resolve(projectRoot, 'packages/onething-runtime/src/scheduler/index.ts') },
  { find: '@onething/runtime/scratchpad', replacement: resolve(projectRoot, 'packages/onething-runtime/src/scratchpad/index.ts') },
  { find: '@onething/runtime/search/protocol', replacement: resolve(projectRoot, 'packages/onething-runtime/src/search/protocol.ts') },
  { find: '@onething/runtime/search', replacement: resolve(projectRoot, 'packages/onething-runtime/src/search/index.ts') },
  { find: '@onething/runtime/voice/kws/text2token', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/kws/text2token.ts') },
  { find: '@onething/runtime/voice/volcano/protocol', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/volcano/protocol.ts') },
  { find: '@onething/runtime/voice/volcano/asr-session', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/volcano/asr-session.ts') },
  { find: '@onething/runtime/voice/volcano/tts-session', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/volcano/tts-session.ts') },
  { find: '@onething/runtime/voice/providers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/providers.ts') },
  { find: '@onething/runtime/voice/text', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/text.ts') },
  { find: '@onething/runtime/voice', replacement: resolve(projectRoot, 'packages/onething-runtime/src/voice/index.ts') },
  { find: '@onething/runtime/providers/model-capability', replacement: resolve(projectRoot, 'packages/onething-runtime/src/providers/model-capability.ts') },
  { find: '@onething/runtime/providers/provider-config', replacement: resolve(projectRoot, 'packages/onething-runtime/src/providers/provider-config.ts') },
  { find: '@onething/runtime/providers/qwen', replacement: resolve(projectRoot, 'packages/onething-runtime/src/providers/qwen.ts') },
  { find: '@onething/runtime/providers/kimi', replacement: resolve(projectRoot, 'packages/onething-runtime/src/providers/kimi.ts') },
  { find: '@onething/runtime/project-dirs/id', replacement: resolve(projectRoot, 'packages/onething-runtime/src/project-dirs/id.ts') },
  { find: '@onething/runtime/project-dirs/persistence', replacement: resolve(projectRoot, 'packages/onething-runtime/src/project-dirs/persistence.ts') },
  { find: '@onething/runtime/project-dirs/prompt', replacement: resolve(projectRoot, 'packages/onething-runtime/src/project-dirs/prompt.ts') },
  { find: '@onething/runtime/project-dirs/store', replacement: resolve(projectRoot, 'packages/onething-runtime/src/project-dirs/store.ts') },
  { find: '@onething/runtime/project-dirs', replacement: resolve(projectRoot, 'packages/onething-runtime/src/project-dirs/index.ts') },
  { find: '@onething/runtime/prompts', replacement: resolve(projectRoot, 'packages/onething-runtime/src/prompts/index.ts') },
  // spaces(workspace 骨架,批 B1)。子路径在 barrel 上方 —— 前缀匹配先到先得。
  { find: '@onething/runtime/spaces/provider-credentials', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/provider-credentials.ts') },
  { find: '@onething/runtime/spaces/credentials', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/credentials.ts') },
  { find: '@onething/runtime/spaces/ipc-operations', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/ipc-operations.ts') },
  { find: '@onething/runtime/spaces/overlay', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/overlay.ts') },
  { find: '@onething/runtime/spaces/persistence', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/persistence.ts') },
  { find: '@onething/runtime/spaces/store', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/store.ts') },
  { find: '@onething/runtime/spaces/types', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/types.ts') },
  { find: '@onething/runtime/spaces', replacement: resolve(projectRoot, 'packages/onething-runtime/src/spaces/index.ts') },
  { find: '@onething/runtime/providers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/providers/index.ts') },
  { find: '@onething/runtime/skills', replacement: resolve(projectRoot, 'packages/onething-runtime/src/skills/index.ts') },
  { find: '@onething/runtime/goals', replacement: resolve(projectRoot, 'packages/onething-runtime/src/goals/index.ts') },
  { find: '@onething/runtime/usage', replacement: resolve(projectRoot, 'packages/onething-runtime/src/usage/index.ts') },
  { find: '@onething/runtime/toc', replacement: resolve(projectRoot, 'packages/onething-runtime/src/toc/index.ts') },
  { find: '@onething/runtime/practice', replacement: resolve(projectRoot, 'packages/onething-runtime/src/practice/index.ts') },
  { find: '@onething/runtime/media', replacement: resolve(projectRoot, 'packages/onething-runtime/src/media/index.ts') },
  { find: '@onething/runtime/music', replacement: resolve(projectRoot, 'packages/onething-runtime/src/music/index.ts') },
  { find: '@onething/runtime/markdown', replacement: resolve(projectRoot, 'packages/onething-runtime/src/markdown/index.ts') },
  { find: '@onething/runtime/themes/base46-parser', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/base46-parser.ts') },
  { find: '@onething/runtime/themes/css-mapper', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/css-mapper.ts') },
  { find: '@onething/runtime/themes/knobs', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/knobs.ts') },
  { find: '@onething/runtime/themes/resolver', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/resolver.ts') },
  { find: '@onething/runtime/themes/role-mapping', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/role-mapping.ts') },
  { find: '@onething/runtime/themes/skin', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/skin.ts') },
  { find: '@onething/runtime/themes/theme-runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/theme-runtime.ts') },
  { find: '@onething/runtime/themes', replacement: resolve(projectRoot, 'packages/onething-runtime/src/themes/index.ts') },
  { find: '@onething/runtime/todo-plan', replacement: resolve(projectRoot, 'packages/onething-runtime/src/todo-plan/index.ts') },
  { find: '@onething/runtime/variables/providers/agent-self', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/agent-self.ts') },
  { find: '@onething/runtime/variables/providers/background-jobs', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/background-jobs.ts') },
  { find: '@onething/runtime/variables/providers/music-radio', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/music-radio.ts') },
  { find: '@onething/runtime/variables/bootstrap', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/bootstrap.ts') },
  { find: '@onething/runtime/variables/providers/core', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/core.ts') },
  { find: '@onething/runtime/variables/providers/datetime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/datetime.ts') },
  { find: '@onething/runtime/variables/providers/git-branch', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/git-branch.ts') },
  { find: '@onething/runtime/variables/providers/global-store', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/global-store.ts') },
  { find: '@onething/runtime/variables/providers/keyed-store', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/keyed-store.ts') },
  { find: '@onething/runtime/variables/providers/goal', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/goal.ts') },
  { find: '@onething/runtime/variables/providers/notes', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/notes.ts') },
  { find: '@onething/runtime/variables/providers/session-store', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/session-store.ts') },
  { find: '@onething/runtime/variables/providers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/providers/index.ts') },
  { find: '@onething/runtime/variables/schema', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/schema.ts') },
  { find: '@onething/runtime/variables/registry', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/registry.ts') },
  { find: '@onething/runtime/variables/format', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/format.ts') },
  { find: '@onething/runtime/variables/validation', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/validation.ts') },
  { find: '@onething/runtime/variables', replacement: resolve(projectRoot, 'packages/onething-runtime/src/variables/index.ts') },
  { find: '@onething/runtime/triggers/skill-review', replacement: resolve(projectRoot, 'packages/onething-runtime/src/triggers/skill-review.ts') },
  { find: '@onething/runtime/triggers/skill-review-state', replacement: resolve(projectRoot, 'packages/onething-runtime/src/triggers/skill-review-state.ts') },
  { find: '@onething/runtime/triggers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/triggers/index.ts') },
  { find: '@onething/runtime/settings', replacement: resolve(projectRoot, 'packages/onething-runtime/src/settings/index.ts') },
  // The catch-all below already resolves this one, but the boundary checker
  // wants每个真实用到的子路径都在表里有名有姓 —— 登记本身就是那条门禁。
  { find: '@onething/runtime/sessions/session-events', replacement: resolve(projectRoot, 'packages/onething-runtime/src/sessions/session-events.ts') },
  // Deep-family catch-alls: leaf modules resolve to <name>.ts; keep them
  // ABOVE the family barrel so the prefix entry cannot swallow them.
  { find: /^@onething\/runtime\/sessions\/(.+)$/, replacement: resolve(projectRoot, 'packages/onething-runtime/src/sessions/$1.ts') },
  { find: '@onething/runtime/sessions', replacement: resolve(projectRoot, 'packages/onething-runtime/src/sessions/index.ts') },
  { find: '@onething/runtime/storage', replacement: resolve(projectRoot, 'packages/onething-runtime/src/storage/index.ts') },
  { find: '@onething/runtime/permissions', replacement: resolve(projectRoot, 'packages/onething-runtime/src/permissions/index.ts') },
  { find: '@onething/runtime/plugins/theme-overrides', replacement: resolve(projectRoot, 'packages/onething-runtime/src/plugins/theme-overrides.ts') },
  { find: '@onething/runtime/plugins/skin', replacement: resolve(projectRoot, 'packages/onething-runtime/src/plugins/skin.ts') },
  { find: '@onething/runtime/plugins', replacement: resolve(projectRoot, 'packages/onething-runtime/src/plugins/index.ts') },
  { find: '@onething/runtime/tools/background-jobs', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/background-jobs.ts') },
  { find: '@onething/runtime/tools/bash-classifier', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/bash-classifier.ts') },
  { find: '@onething/runtime/tools/bash-executor', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/bash-executor.ts') },
  { find: '@onething/runtime/tools/edit-engine', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/edit-engine.ts') },
  { find: '@onething/runtime/tools/file-mutation-audit', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/file-mutation-audit.ts') },
  { find: '@onething/runtime/tools/file-mutation-queue', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/file-mutation-queue.ts') },
  { find: '@onething/runtime/tools/file-snapshot', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/file-snapshot.ts') },
  { find: '@onething/runtime/tools/output-accumulator', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/output-accumulator.ts') },
  { find: '@onething/runtime/tools/replacers', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/replacers.ts') },
  { find: '@onething/runtime/tools/sandbox-runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/sandbox-runtime.ts') },
  { find: '@onething/runtime/tools/sandbox', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/sandbox.ts') },
  { find: '@onething/runtime/tools/sensitive-files', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/sensitive-files.ts') },
  { find: '@onething/runtime/tools/text-truncation', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/text-truncation.ts') },
  { find: '@onething/runtime/tools', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tools/index.ts') },
  { find: '@onething/runtime/tasks', replacement: resolve(projectRoot, 'packages/onething-runtime/src/tasks/index.ts') },
  { find: '@onething/runtime/perf', replacement: resolve(projectRoot, 'packages/onething-runtime/src/perf/index.ts') },
  { find: '@onething/runtime', replacement: resolve(projectRoot, 'packages/onething-runtime/src/index.ts') },
]
}
