export {
  AgentEngine,
  createEchoAgentProvider,
} from '@onething/backend/runtime/agents/agent-engine-exports'
export type {
  AgentEngineOptions,
  AgentEngineProvider,
  AgentEngineRequest,
  AgentEngineSessionEvent,
  AgentEngineStreamChunk,
  AgentEngineUsage,
  SendMessageOptions,
  SendMessageResult,
} from '@onething/backend/runtime/agents/agent-engine-exports'

export {
  AgentEventQueue,
  AgentLoopPauseForConfirmationError,
  abortableAgentEvents,
  agentContentFromHistoryContent,
  agentContentToText,
  agentEventToChunk,
  agentEventsToProviderStreamChunks,
  agentMessagesFromHistory,
  agentModelToolsFromDefinitions,
  agentProviderCanRunTurn,
  agentSupportsCapability,
  agentSupportsForcedToolUse,
  agentSupportsInputModality,
  agentSupportsOutputModality,
  agentSupportsStructuredToolResults,
  agentSupportsToolResultModality,
  agentSupportsTools,
  agentToolCallsFromHistory,
  agentToolDefinitionsFromSourceTools,
  agentToolMessageContentForCapabilities,
  agentToolMessageContentToStructuredPayload,
  agentToolMessageContentToText,
  agentToolResultToMessageContent,
  agentToolResultToMessageContentForCapabilities,
  agentToolsFromToolDefinitions,
  applyPromptInjectors,
  assertAgentMessagesSupportedByCapabilities,
  assertAgentOutputModalitiesSupportedByCapabilities,
  assertAgentProviderCanRunTurn,
  buildAgentLoopRuntime,
  buildSkillPrompt,
  collectAgentTurnFromStream,
  createAgentAbortError,
  clearRetiredAgentToolNames,
  createAIToolName,
  createSkillPromptInjector,
  createSystemPromptInjector,
  getAIToolName,
  inputModalitiesFromAgentContent,
  isAgentLoopPauseForConfirmationError,
  isAgentRunnableProvider,
  isAgentStreamingProvider,
  isCompleteAgentToolArguments,
  mapAgentProviderFinishReason,
  needsOrderedSideEffectGate,
  OrderedSideEffectQueue,
  providerSupportsCapability,
  providerSupportsInputModality,
  providerSupportsOutputModality,
  providerSupportsToolResultModality,
  registerRetiredAgentToolName,
  resolveAgentModelCapabilities,
  resolveAIToolName,
  resolveRetiredAgentToolName,
  runAgentLoop,
  runWithAgentAbort,
  safeParseAgentToolArguments,
  streamAgentLoopProviderChunks,
  streamAgentProviderTurnEvents,
  ToolExecutionScheduler,
  throwIfAgentAborted,
  TEXT_ONLY_AGENT_CAPABILITIES,
} from './agent-loop/index.js'
export type {
  AgentAfterTurnHook,
  AgentAudioContentPart,
  AgentBeforeTurnHook,
  AgentCapability,
  AgentContentPart,
  AgentExecutableProvider,
  AgentFileContentPart,
  AgentFinishReason,
  AgentHistoryContent,
  AgentHistoryMessage,
  AgentImageContentPart,
  AgentInputModality,
  AgentJsonObject,
  AgentJsonValue,
  AgentLoopOptions,
  AgentLoopResult,
  AgentLoopStreamChunk,
  AgentLoopToolResult,
  AgentMessage as AgentLoopMessage,
  AgentMessageContent,
  AgentModelCapabilities,
  AgentModelToolDefinition,
  AgentOutputModality,
  AgentProviderData,
  AgentProviderStreamAdapterOptions,
  AgentProviderStreamChunk,
  AgentProviderStreamFinishReason,
  AgentProviderToolCallChunk,
  AgentProvider as AgentLoopProvider,
  AgentPromptInjectionContext,
  AgentPromptInjector,
  AgentRole,
  AgentRunnableProvider,
  AgentRuntimePromptOptions,
  AgentRuntimeToolOptions,
  AgentSkillContext,
  AgentSourceToolDefinition,
  AgentStreamEvent,
  AgentStreamingProvider,
  AgentTextContentPart,
  AgentTool,
  AgentToolCall,
  AgentToolChoice,
  AgentToolExecutionAdapter,
  AgentToolExecutionAdapterResult,
  AgentToolExecutionContext,
  AgentToolMetadataUpdate,
  AgentToolPartialResultUpdate,
  AgentToolPolicy,
  AgentToolResult,
  AgentToolResultContentPart,
  AgentTurn,
  AgentTurnLifecycleContext,
  AgentTurnRequest,
  AgentTurnStreamEvent,
  AgentUsage,
  AgentVideoContentPart,
  BuildAgentLoopRuntimeOptions,
  ToolExecutionScheduleOptions,
} from './agent-loop/index.js'

// MCP 内核(原 `./mcp/`)第③步(2026-10-02)并进了 `runtime/mcp/kernel/` —— 它只有 mcp 领域与脊柱在用,
// 不是通用骨架。core 的桶不再再导出它(那会让 core 倒挂到 runtime);要用就 import `@onething/backend/runtime/mcp/kernel`。
// 搬家前查过:没有一处经这只桶拿 MCP 的名字。

export type {
  Provider,
  ProviderFinishReason,
  ProviderRequest,
  ProviderStreamEvent,
  ProviderUsage,
} from '@onething/backend/runtime/providers/stream-provider-contract'

export type {
  CoreAfterAssistantResponseContext,
  CoreAfterAssistantResponseHook,
  CoreBeforeContextCompactContext,
  CoreBeforeContextCompactHook,
  CorePluginDefinition,
  CorePluginAPIState,
  CorePluginAPIHost,
  CorePluginAPILogger,
  CorePluginHostToolContext,
  CorePluginHostToolResult,
  CorePluginLifecycleLogger,
  CorePluginInfo,
  CorePluginManagerHost,
  CorePluginManagerLogger,
  CorePluginScheduledTaskLike,
  CorePluginStateLike,
  CorePluginSchedulerHandleLike,
  CorePluginSchedulerHost,
  CreateScopedPluginSchedulerOptions,
  PluginManifest,
  PluginSettings,
  PluginSource,
  PluginTaskSnapshotLike,
} from './plugins/index.js'
export {
  CorePluginLifecycleRegistry,
  CorePluginManager,
  CorePluginStore,
  createCorePluginAPI,
  createScopedPluginScheduler,
  disposeCorePluginState,
  executeCorePluginTool,
  isPluginTaskSnapshot,
  scopePluginTaskId,
  unscopePluginTaskId,
  unscopePluginTaskSnapshot,
  DEFAULT_PLUGIN_ENTRY,
  getPluginEnabledFromSettings,
  parsePluginDirectory,
  readPluginSettingsFile,
  scanPluginDirectories,
  setPluginEnabledInSettings,
  writePluginSettingsFile,
} from './plugins/index.js'
export type {
  PluginStoreOptions,
} from './plugins/index.js'

export {
  DEFAULT_INTERACTION_ABORTED_REASON,
  DEFAULT_INTERACTION_DECLINED_REASON,
  DEFAULT_INTERACTION_TIMEOUT_MS,
  DEFAULT_INTERACTION_TIMEOUT_REASON,
  Interaction,
} from '@onething/backend/runtime/interaction'
export type {
  InteractionBusEvent,
  InteractionCommandEnvelope,
  InteractionEventBusLike,
  InteractionRespondCommandLike,
} from '@onething/backend/runtime/interaction'

export {
  Permission,
  addGrant,
  clearSessionGrants,
  clearWorkspaceGrants,
  configurePermissionGrantStorage,
  decidePermission,
  enforcePermissionPolicy,
  listSessionGrants,
  listWorkspaceGrants,
  matchGrant,
  resetPermissionGrantsForTests,
  revokeGrant,
} from '@onething/backend/runtime/permission/permission-asks'
export type {
  EnforcePermissionPolicyInput,
  PermissionCommandEnvelope,
  PermissionEffect,
  PermissionEventBusLike,
  PermissionGrantInput,
  PermissionGrantMatchInput,
  PermissionGrantOwner,
  PermissionGrantStorage,
  PermissionPolicyDecision,
  PermissionPolicyInput,
  PermissionPolicyMode,
  PermissionPolicyResult,
  PermissionPreview,
  PermissionRespondCommandLike,
} from '@onething/backend/runtime/permission/permission-asks'

export {
  createCoreCachedJsonState,
  deleteJsonFile,
  ensureDir,
  getCoreCachedJsonFile,
  AsyncSaveQueue,
  getPluginDataDir,
  initializeCoreCachedJsonFile,
  invalidateCoreCachedJsonFile,
  isCoreCachedJsonInitialized,
  LRUCache,
  readJsonFile,
  saveCoreCachedJsonFile,
  saveCoreCachedJsonFileAsync,
  updateCoreCachedJsonInMemory,
  writeJsonFile,
  writeJsonFileAsync,
} from '@onething/backend/runtime/storage/storage-primitives'
export type {
  AsyncSaveQueueOptions,
  CoreCachedJsonFileOptions,
  CoreCachedJsonState,
} from '@onething/backend/runtime/storage/storage-primitives'

export {
  AllowAllPolicy,
  DenyAllPolicy,
  ToolExecutor,
  ToolRegistry,
  coreToolContextFromHost,
  coreToolValidationFailureMessage,
  coreToolDefinitionFromJsonSchema,
  coreToolParameterFromSchema,
  executeToolCalls,
  extractCoreErrorMessage,
  isBarrierEffect,
  normalizeCoreToolParameterType,
  isAutoExecutePermissionGuard,
  isInjectablePermissionGuard,
} from '@onething/backend/runtime/tools/tool-helpers'
export type {
  CoreToolPermissionGuard,
  CoreToolPermissionGuardLike,
  CoreMaybePromise,
  CoreToolDefinitionFromJsonSchemaInput,
  CoreToolFailureResult,
  CoreToolHostExecutionContext,
  CoreToolJsonSchemaLike,
  CoreToolParameterDefinition,
  CoreToolParameterType,
  CoreToolValidationResult,
  ToolEffect,
  ToolEffectKind,
  ToolEffectMetadata,
  ToolEffectMetadataValue,
  ToolPreview,
  PermissionPolicy,
  ToolCall,
  ToolDefinition,
  ToolExecutionContext,
  ToolExecutorOptions,
  ToolResult,
} from '@onething/backend/runtime/tools/tool-helpers'

export {
  ContextManager,
} from '@onething/backend/runtime/context'
export type {
  AgentMessage,
  AgentMessageRole,
} from '@onething/backend/runtime/context'

export {
  isCoreConversationRuntime,
  isCoreTextStreamChunk,
} from './gateway-runtime.js'
export type {
  CoreConversationEngineLike,
  CoreConversationEventBusLike,
  CoreConversationEventEnvelopeLike,
  CoreConversationRuntime,
  CoreConversationRuntimeFactoryOptions,
  CoreConversationSendMessageCommand,
  CorePermissionDecision,
  CorePermissionMode,
  CorePermissionRequestEvent,
  CorePermissionSurface,
  CoreSendMessageOptions,
  CoreSessionRuntime,
  CoreStreamChannelLike,
  CoreTextStreamChunk,
} from './gateway-runtime.js'

export {
  canApplyGeneratedSessionTitle,
  CoreStreamEngine,
  CoreTriggerManager,
  createCoreId,
  createCoreEventOnlyEmitter,
  generateTitleFromMessage,
  normalizeSessionTitle,
  PendingMessageQueue,
  resolveToolCallModel,
} from './engine/index.js'
export type {
  AbortLikeCommand,
  CoreCommandEnvelope,
  CoreContextCompactResultLike,
  CoreEventBusEmitterLike,
  CoreEventOnlyEventBusLike,
  CoreEventOnlyLogger,
  CoreEventOnlySessionEvent,
  CoreEventOnlyStoreHooks,
  CoreEventOnlyStreamChannelLike,
  CoreEventOnlyStreamChunk,
  CoreIPCEmitter,
  CoreProviderConfigWithKeyLike,
  CoreReasoningPlacement,
  CoreStreamEngineOptions,
  CoreStreamEngineRuntime,
  CoreStreamErrorInfo,
  CoreStreamCompleteData,
  CoreStreamErrorData,
  CoreStreamMessage,
  CoreStreamResultLike,
  CoreStreamSession,
  CoreStreamSettings,
  CoreTrigger,
  CoreTriggerContext,
  CoreTriggerManagerLogger,
  CreateCoreEventOnlyEmitterOptions,
  InjectMessageCommand,
  PendingMessage,
  QueueMode,
  StreamEngineProviderConfigLike,
  StreamEngineSettingsWithProviders,
  StreamEngineToolCallModelSettings,
} from './engine/index.js'

export {
  EventBus,
  RingBuffer,
  StreamChannel,
} from '@onething/backend/runtime/event-bus'
export type {
  EmitResult,
  EventBase,
  GlobalEventEnvelope,
  GlobalObserveHandler,
  InterceptHandler,
  InterceptResult,
  ObserveHandler,
  SessionEventEnvelope,
  StreamChunkHandler,
  TypedObserveHandler,
  Unsubscribe,
} from '@onething/backend/runtime/event-bus'

export {
  Session,
  SessionManager,
  createEmptySessionState,
  deriveRetainedContextSize,
  decodeMessagePageCursor,
  encodeMessagePageCursor,
  getCoreSessionManager,
  getMessagesPageFromArray,
  getMessagesPageFromJson,
  getUserMessageMarkersFromArray,
  initializeCoreSessionLayer,
  isCoreSessionLayerInitialized,
  formatSessionValidationResult,
  repairSessionTimelineMetadata,
  sanitizeInterruptedStepRecursive,
  sanitizeLoadedSession,
  sanitizeSessionOnStartup,
  shutdownCoreSessionLayer,
  validateSessionStateConsistency,
} from './session/index.js'
export type {
  CoreSessionValidationInput,
  CoreSessionValidationResult,
  CoreSessionRepository,
  CoreTimelineMessage,
  CoreTimelineSession,
  CoreTimelineStep,
  CoreTokenUsage,
  CoreToolCallState,
  GetSessionMessagesPageRequest,
  GetSessionMessagesPageResponse,
  SessionMessagePageCursor,
  SessionMessagesPageAnchor,
  SessionMessagesPageDirection,
  SessionState,
  StoredChatMessage,
  TurnUsage,
  TimelineMetadataRepairOptions,
  UserMessageMarker,
} from './session/index.js'

export {
  createOnethingRuntimeFacade,
} from './runtime-facade.js'
export type {
  OnethingRuntimeFacade,
  OnethingRuntimeFacadeOptions,
  RuntimeAppStateAdapter,
  RuntimeCapabilitiesAdapter,
  RuntimeEventEnvelope,
  RuntimeEventsAdapter,
  RuntimeEventSubscribeOptions,
  RuntimeGlobalEventsAdapter,
  RuntimeMessagesAdapter,
  RuntimeMutationResult,
  RuntimeOAuthAdapter,
  RuntimeOAuthTokenEvent,
  RuntimePermissionsAdapter,
  RuntimeRequestContext,
  RuntimeSessionsAdapter,
  RuntimeStreamPayload,
  RuntimeStreamsAdapter,
  RuntimeUnsubscribe,
  RuntimeVoiceAdapter,
} from './runtime-facade.js'
