export * from './music-types.js'
export * from './music-ncm-cli-driver.js'
export * from './music-setup-service.js'
export * from './music-ipc-operations.js'
export * from './music-now-playing.js'
export * from './music-radio-store.js'
export * from './music-reliable-runner.js'
export * from './music-radio-conductor.js'
export * from './music-radio-render.js'
export * from './music-lyrics.js'
export * from './music-identify.js'
export * from './providers/music-providers.js'
// 音乐 CLI 的 bash 分类策略登记(越层清零 C8):装配时调一次。
export { registerMusicBashPolicies } from './music-bash-policies.js'
