import {
  Brain,
  Gauge,
  ListChecks,
  ImagePlus,
  Mic,
  FolderTree,
  Folder,
  FolderOpen,
  GitCompare,
  Terminal,
  FileText,
  File,
  FileCode,
  FileBraces,
  FileSpreadsheet,
  FileImage,
  Image,
  FileArchive,
  FileMusic,
  FilePlay,
  FileTerminal,
  FileCog,
  FileLock,
  Pencil,
  Wrench,
  SlidersHorizontal,
  Globe,
  Settings,
  LayoutGrid,
  Plus,
  X,
  Pin,
  PictureInPicture2,
  Maximize2,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronsLeft,
  ChevronsUp,
  ChevronsDown,
  Search,
  Check,
  Eye,
  EyeOff,
  Minus,
  Info,
  CircleCheck,
  CircleAlert,
  Paperclip,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  RotateCw,
  Ellipsis,
  Copy,
  TriangleAlert,
  Bell,
  Square,
  Boxes,
  Layers,
  MessageSquare,
  MessagesSquare,
  Users,
  ArrowLeftRight,
  SquareCheck,
  Zap,
  PinOff,
  Columns2,
  Rows2,
  Unlink,
  Music,
  Disc3,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Heart,
  // 音乐面 v7:歌条上的两颗新钮 —— 播放列表(一张带音符的单子)与歌词(一支人声麦)。
  ListMusic,
  Volume2,
  MicVocal,
  // 09-14 引用 chip 皮 B:技能那一枚的真图标(从前是一个 ◇ 字符记号)。
  Sparkles,
  // B3-b:设置页「身份」那一行的删钮(X 会被读成「关掉」;会删数据的钮该长得像删)。
  Trash2,
  // 09-18 列表换序(`ui/list-reorder`)那颗把手。**竖排的那一枚**:它说的是
  // 「这一行在一列里上下挪」,横排的 `GripHorizontal` 说的是左右挪 —— 两枚形近
  // 而意不同,拿错一枚等于在屏幕上说反了方向。
  GripVertical,
  // 音乐面 v9(09-25):檐上导航「电台」一格、账号那颗钮、没登录时的「登录」。
  Radio,
  CircleUserRound,
  LogIn,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * item 只写图标「名字」(一个字符串),不许直接持有组件 ——
 * 这样 items 表将来可以来自 JSON / 后端而不牵动渲染层。
 */
const REGISTRY: Record<string, LucideIcon> = {
  Brain,
  ImagePlus,
  Mic,
  FolderTree,
  Folder,
  FolderOpen,
  GitCompare,
  Terminal,
  FileText,
  File,
  FileCode,
  FileBraces,
  FileSpreadsheet,
  FileImage,
  Image,
  FileArchive,
  FileMusic,
  FilePlay,
  FileTerminal,
  FileCog,
  FileLock,
  Pencil,
  Wrench,
  /* 「配置这一型」的滑杆(模型目录行尾第三颗钮)。Settings 那枚齿轮在这套词汇
     里已经是「设置面」本身,拿它当行内的逐型配置口会被读成「打开设置」。 */
  SlidersHorizontal,
  Globe,
  Settings,
  LayoutGrid,
  Plus,
  X,
  Pin,
  PictureInPicture2,
  Maximize2,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronsLeft,
  ChevronsUp,
  ChevronsDown,
  Search,
  Check,
  Eye,
  EyeOff,
  Minus,
  Info,
  CircleCheck,
  CircleAlert,
  Paperclip,
  ArrowUp,
  /* 浏览器导航那一族(B2):后退 / 前进用**箭头**而不是 chevron —— 全世界的
     浏览器都用这一对,而 chevron 在这套词汇里已经是「展开 / 收起」。
     `RotateCw` 是刷新(顺时针,同样是浏览器的通用形);已有的 `RotateCcw`
     是「重试」,两者形近而意不同,所以各占一格不合并。 */
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  RotateCw,
  Ellipsis,
  Copy,
  TriangleAlert,
  Bell,
  Square,
  Boxes,
  Layers,
  /* 单气泡 = 「就是一条聊天」(expose 的 loose 范围)。空心方框 `Square` 在这套
     词汇里已经是 composer 的「停止」,拿它当范围图标会被读成一枚勾选框
     —— 09-04 真机走查用户看图当场指出的那一格。 */
  MessageSquare,
  MessagesSquare,
  /* 会话行的形态字形(expose/row-kinds 的 RowGlyph → 这五格,SessionRow 读表)。 */
  Users,
  ArrowLeftRight,
  SquareCheck,
  Zap,
  PinOff,
  /* 分屏两向(W1 叶檐的动作组):竖切成两列 / 横切成两行。形说的是**切完的样子**,
     不是「往哪边推」—— 与架子那族的方向箭头分得开。 */
  Columns2,
  Rows2,
  /* 「拆开」(W6-a 两格标签的格头):一条断开的链 —— 说的是「这两格不再连在
     一起」,与分屏那两枚「切完的样子」正交。 */
  Unlink,
  /* 音乐这一族(音乐收尾 · 壳半边)。逐枚说的都是**面里有什么**,不是它长什么样:
     Music(那块瓦:一枚音符,面里就是音乐)/ Disc3(没有封面时那一格的字形 —— 见 MusicPanel 头上
     「封面」那一段:这台上没有封面这件事实,所以画的是唱片本身不是一张假图)/
     Play · Pause · SkipBack · SkipForward · Heart(播放器那五颗,全世界同一套形)。 */
  Music,
  Disc3,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Heart,
  ListMusic,
  // 音量(09-19:音乐面控制栏的音量杆前面那一枚)。
  Volume2,
  MicVocal,
  // 我的清单(待办 T3)那块瓦。
  ListChecks,
  // 内存面板的 Dock 图标。
  Gauge,
  Sparkles,
  Trash2,
}

export function resolveIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? FolderTree
}

export {
  Brain,
  ListChecks,
  Image,
  ImagePlus,
  Mic,
  Pencil,
  Wrench,
  SlidersHorizontal,
  Plus,
  X,
  Pin,
  PictureInPicture2,
  Maximize2,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronsLeft,
  ChevronsUp,
  ChevronsDown,
  Search,
  Check,
  Eye,
  EyeOff,
  Minus,
  Info,
  CircleCheck,
  CircleAlert,
  Paperclip,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  RotateCw,
  Ellipsis,
  Copy,
  TriangleAlert,
  Bell,
  Square,
  Layers,
  MessageSquare,
  Users,
  ArrowLeftRight,
  SquareCheck,
  Zap,
  PinOff,
  Columns2,
  Rows2,
  Unlink,
  Music,
  Disc3,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Heart,
  ListMusic,
  Volume2,
  MicVocal,
  Trash2,
  GripVertical,
  Radio,
  CircleUserRound,
  LogIn,
}
export type { LucideIcon }
