// 兼容桶:只做转发,名字取自各功能入口(包根归位 2,2026-10-03:原先经 `stores/index.ts` 转一手,那只桶已删)。
// 留着它是因为 59 处测试 `vi.mock` 打在这只文件上,拆那批 mock 另起一笔;新代码直接从功能入口取名字。
// 这一笔顺手删掉了没有任何使用者的 7 个名字(`initializeStores` 等)。
export { getSettings, saveSettings } from '@onething/backend/runtime/settings'
export { getCurrentSessionId, setCurrentSessionId } from '@onething/backend/runtime/sessions'
export {
  getSessions,
  getSession,
  createSession,
  createSessionWithoutFocus,
  createBranchSession,
  deleteSession,
  onSessionsDeleted,
  renameSession,
  updateSessionPin,
  updateSessionArchived,
  updateMessageContent,
  updateMessageReasoning,
  updateMessageStreaming,
  updateMessageUsage,
  updateMessageToolCalls,
  updateMessageContentParts,
  addMessageContentPart,
  updateMessageThinkingTime,
  updateMessageSkill,
  updateMessageError,
  updateMessageTurnContext,
  addMessageStep,
  updateMessageStep,
  updateMessageSteps,
  updateStepsUsageByTurn,
  updateSessionSummary,
  updateSessionModel,
  updateSessionAgent,
  updateSessionCollab,
  updateSessionTask,
  updateSessionPermissionMode,
  updateSessionWorkingDirectory,
  updateSessionWorkingDirectoryRoots,
  updateSessionVariables,
  updateSessionGoal,
  updateSessionGoals,
  updateSessionContextSize,
  getSessionTokenUsage,
  getSessionsList,
  getSessionDetails,
  getSessionMessages,
  getSessionMessagesPage,
  getSessionUserMessageMarkers,
  flushSessionSave,
  flushAllPendingSaves,
  patchSessionFields,
  invalidateSessionCache,
  getSessionCacheStats,
} from '@onething/backend/runtime/sessions'
