// This file re-exports from the new modular store structure
// for backwards compatibility with existing imports

export {
  // Settings
  getSettings,
  saveSettings,

  // App state
  getCurrentSessionId,
  setCurrentSessionId,

  // Sessions
  getSessions,
  getSession,
  createSession,
  createSessionWithoutFocus,
  createBranchSession,
  deleteSession,
  onSessionsDeleted,
  renameSession,
  updateSessionPin,
  updateSessionArchived,
  addMessage,
  deleteMessage,
  deleteMessageAndTruncate,
  updateMessageAndTruncate,
  updateMessageContent,
  updateMessageReasoning,
  updateMessageStreaming,
  updateMessageUsage,
  updateMessageToolCalls,
  updateMessageContentParts,
  addMessageContentPart,
  updateMessageThinkingTime,
  updateMessageSkill,
  updateMessageError,
  updateMessageTurnContext,
  addMessageStep,
  updateMessageStep,
  updateMessageSteps,
  updateStepsUsageByTurn,
  updateSessionSummary,
  updateSessionModel,
  updateSessionAgent,
  updateSessionCollab,
  updateSessionTask,
  updateSessionPermissionMode,
  updateSessionWorkingDirectory,
  updateSessionWorkingDirectoryRoots,
  updateSessionVariables,
  updateSessionGoal,
  updateSessionGoals,
  inheritSessionWorkingDirectory,
  updateSessionTokenUsage,
  updateSessionContextSize,
  updateSessionPromptContext,
  getSessionTokenUsage,
  deriveRetainedContextSize,
  // Optimized session loading (Phase 4: Metadata Separation)
  getSessionsList,
  getSessionDetails,
  getSessionMessages,
  getSessionMessagesPage,
  getSessionUserMessageMarkers,
  initializeSessionRepositoryIndex,
  flushSessionSave,
  flushAllPendingSaves,
  patchSessionFields,
  invalidateSessionCache,
  getSessionCacheStats,

  // Initialization
  initializeStores,
} from './stores/index.js'
