import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { encodeOnethingKeywordPhrase, parseOnethingKwsTokenVocabulary } from '../kws/text2token'

// The bundled wenetspeech KWS vocabulary the app ships with.
const tokensFile = readFileSync(
  resolve(__dirname, '../../../../../resources/models/kws/tokens.txt'),
  'utf8',
)

describe('kws text2token', () => {
  it('parses the vocabulary file', () => {
    const vocabulary = parseOnethingKwsTokenVocabulary(tokensFile)
    expect(vocabulary.has('<blk>')).toBe(true)
    expect(vocabulary.has('zh')).toBe(true)
    expect(vocabulary.has('ǐ')).toBe(true)
  })

  it('matches the official encoding for known keywords', () => {
    // Reference lines from the model's own keywords.txt (generated by
    // sherpa-onnx-cli text2token --tokens-type ppinyin).
    expect(encodeOnethingKeywordPhrase('小爱同学', tokensFile).line)
      .toBe('x iǎo ài t óng x ué @小爱同学')
    expect(encodeOnethingKeywordPhrase('你好军哥', tokensFile).line)
      .toBe('n ǐ h ǎo j ūn g ē @你好军哥')
    expect(encodeOnethingKeywordPhrase('小艺小艺', tokensFile).line)
      .toBe('x iǎo y ì x iǎo y ì @小艺小艺')
    expect(encodeOnethingKeywordPhrase('你好问问', tokensFile).line)
      .toBe('n ǐ h ǎo w èn w èn @你好问问')
  })

  it('appends boosting score and trigger threshold suffixes', () => {
    const { line } = encodeOnethingKeywordPhrase('小米小米', tokensFile, {
      boostingScore: 2,
      triggerThreshold: 0.35,
    })
    expect(line).toBe('x iǎo m ǐ x iǎo m ǐ :2 #0.35 @小米小米')
  })

  it('rejects non-Chinese phrases and empty input', () => {
    expect(() => encodeOnethingKeywordPhrase('hey onething', tokensFile)).toThrow(/Chinese/)
    expect(() => encodeOnethingKeywordPhrase('  ', tokensFile)).toThrow(/empty/)
  })

  it('reports characters outside the vocabulary', () => {
    expect(() => encodeOnethingKeywordPhrase('你好', 'n 0\nǐ 1\n')).toThrow(/vocabulary/)
  })
})
